code-obos/grunnmuren

.github/workflows/main.yml
.github/workflows/release.yml
pnpm-lock.yaml

upgrade pnpm to the latest version, 7.

use pnpm 7

---

.changeset/rich-moose-occur.md
packages/tailwind/README.md
packages/tailwind/tailwind-base.cjs

with an option for using the old font

use new OBOS font in Tailwind preset

---

.github/workflows/main.yml
.gitignore

Deploy the Storybookt to GH pages using [this action](https://github.com/marketplace/actions/deploy-to-github-pages)

deploy Storybook to GH pages

---

.changeset/chatty-ears-think.md
packages/react/src/Stepper/Stepper.tsx
packages/react/src/Stepper/index.ts
packages/react/src/Stepper/stories/Stepper.stories.tsx
packages/react/src/index.ts

Add the Stepper component from Figma https://www.figma.com/file/XRHRRytz9DqrDkWpE4IKVB/OBOS-DS?node-id=3180%3A54316.
edit: added screenshots

add Stepper component

---

.changeset/mighty-shoes-rest.md
packages/react/src/Checkbox/Checkbox.tsx
packages/tailwind/tailwind-base.cjs
pnpm-lock.yaml

Fix checkbox bg color

---

packages/react/package.json
pnpm-lock.yaml

fixes the publishing issue where changesets major bumps the React package due to the peer dep being out of range

change the peer dep range in React package

---

.changeset/spotty-apes-draw.md
packages/tailwind/tailwind-base.cjs

See https://www.figma.com/file/XRHRRytz9DqrDkWpE4IKVB/OBOS-DS?node-id=777%3A9628

less rounding of page content corners

---

.changeset/brown-dolphins-begin.md
.changeset/gold-chairs-glow.md
packages/react/package.json
packages/react/src/Accordion/Accordion.tsx
packages/react/src/Accordion/index.tsx
packages/react/src/Accordion/stories/Accordion.stories.tsx
packages/react/vite.config.js
pnpm-lock.yaml

Implementerer Accordion i henhold til figma skissene. For det meste kopiert over fra Medlemsteamet sin Accordion, og lagt til mer riktig bruk av fokus styles
Valgte å ikke tvinge padding over og under da noen bruker tailwind-typography pluginen, og den legger til padding på y-aksen, så var litt usikker på om det er noe vits å ta med da. 
Figma: https://www.figma.com/file/XRHRRytz9DqrDkWpE4IKVB/OBOS-DS?node-id=1734%3A20158

React accordions

---

packages/react/.storybook/main.js

See https://storybook.js.org/docs/react/configure/telemetry#how-to-opt-out

disable storybook telemetry

---

.changeset/quick-schools-kiss.md
packages/react/src/Accordion/Accordion.tsx
packages/react/src/Accordion/stories/Accordion.stories.tsx

Multiple AccordionItems should have an 8 px gap between them, while the accordioncontent bottom padding should be 2x the top padding.

add Accordion. Increase AccordionContent bottom padding

---

.changeset/swift-rivers-own.md
packages/react/src/Chip/Chip.tsx

Oppdaterte chips designet slik at det er nærmere figma designet

Finalized chips

---

.changeset/gentle-worms-repeat.md
packages/tailwind/tailwind-base.cjs

Changed maxwidth and width prose to 696px

---

.changeset/little-wolves-smash.md
packages/tailwind/tailwind-base.cjs

We forgot this in https://github.com/code-obos/grunnmuren/pull/196.

update .container-prose max-width to 696px

---

.changeset/clever-mice-refuse.md
packages/react/src/Radio/RadioGroup.tsx
packages/react/src/TextArea/TextArea.tsx
packages/react/src/TextField/TextField.tsx

Legger til støtte for ReactNode for description-prop i TextField, RadioGroup og Textarea

Changes text field description reactnode

---

.changeset/many-spies-provide.md
packages/react/src/Banner/Banner.tsx
packages/react/src/Campaign/Campaign.tsx
packages/react/src/Hero/Hero.tsx
packages/react/src/Hero/HeroContent.tsx
packages/react/src/Navbar/stories/Navbar.stories.tsx
packages/react/src/Snackbar/Snackbar.tsx
packages/tailwind/tailwind-base.cjs

refact: use Tailwind modifier for max screen width

---

.changeset/chatty-emus-doubt.md
packages/tailwind/package.json

Doing this as a minor since everything is backwards compatible

change Tailwind peer dep to 3.2

---

.changeset/young-phones-carry.md
packages/react/src/Navbar/NavbarItem.tsx
packages/tailwind/tailwind-base.cjs

[#62817](https://dev.azure.com/obosbbl/Content%20hub/_boards/board/t/Team%20Nettsted%20og%20B2B/Stories/?workitem=62817)

Deprecate fake-font-bold and use font-bold instead

---

.changeset/nice-carrots-perform.md
packages/react/src/StepList/StepList.tsx

Etter avklaring med Hanna, endrer vi slik at vi sentrerer tekst i StepList. Endret i Figma: https://www.figma.com/file/XRHRRytz9DqrDkWpE4IKVB/OBOS-DS?node-id=3180%3A54477&t=zkxzVyibMvClTBVg-0
[#63111](https://dev.azure.com/obosbbl/Content%20hub/_boards/board/t/Team%20Nettsted%20og%20B2B/Stories/?workitem=63111)

Step list change text to be centered

---

.changeset/bright-hounds-allow.md
packages/react/src/Card/CardContent.tsx

so it matches [Figma specs](https://www.figma.com/file/XRHRRytz9DqrDkWpE4IKVB/OBOS-DS?node-id=325%253A1258)

card: reduce vertical padding in card content on desktop

---

.changeset/early-scissors-study.md
.changeset/eighty-humans-move.md
packages/react/src/Form/FormErrorMessage.tsx
packages/react/src/Input/Input.tsx

Adjust spacing and roundedness for inputs and error messages so it matches the Figma design

Minor form elements adjustments

---

.changeset/short-camels-worry.md
packages/react/src/Hero/Hero.tsx
packages/react/src/Hero/HeroActions.tsx
packages/react/src/Hero/HeroContent.tsx
packages/react/src/Hero/HeroImage.tsx

Legger til ref support på hero komponentene

Add ref support to hero components

---

.changeset/eleven-eggs-confess.md
packages/react/src/Snackbar/Snackbar.tsx

Update snackbar design so that it is closer to the figma design https://www.figma.com/file/XRHRRytz9DqrDkWpE4IKVB/OBOS-DS?node-id=2164%3A36268&t=0HoiyaX4Lg5f0O5K-0
Minimalt med endringer egentlig. Så kjører den som en patch

Snackbar: update design

---

.changeset/silent-waves-call.md
packages/react/src/hooks/index.ts

Fikser exports av react-use. Skal bare være en patch siden brukerne vil ikke merke noe forskjell

fix react-use exports

---

.github/workflows/main.yml
.github/workflows/release.yml
pnpm-lock.yaml

Upgrade pnpm to v8 and upgrade the lockfile to the new format

upgrade pnpm to v8

---

.changeset/lazy-papayas-bathe.md
packages/react/src/Form/MultiStep/FormStep.tsx

Tror det skal fikse denne bugen jeg får når jeg bruker pakka:

Formstep fix use update effect import

---

.changeset/chilly-shrimps-attend.md
packages/react/package.json
packages/react/src/Form/MultiStep/FormStep.tsx
packages/react/src/hooks/index.ts
packages/react/src/hooks/usePrefersReducedMotion.ts
packages/react/src/hooks/useScreenMaxWidthMd.ts
packages/react/vite.config.js
pnpm-lock.yaml

Fjerner react-use og bruker react-hookz.

switch from react-use to @react-hookz

---

.changeset/kind-clouds-return.md
packages/react/package.json
packages/react/src/Select/Select.tsx
packages/react/src/TextArea/TextArea.tsx
packages/react/src/TextField/TextField.tsx
packages/react/vite.config.js
pnpm-lock.yaml

fjerner react-hook/merged-refs og bytter ut med react-merge-refs

remove merged-refs and use react-merge-refs instead

---

.changeset/honest-tigers-mix.md
packages/react/src/Form/MultiStep/FormStepContext.tsx

Expose setActiveStep from useFormContext

expose setActiveStep

---

packages/tailwind/README.md
packages/tailwind/package.json
packages/tailwind/tailwind-base.cjs
pnpm-lock.yaml

Denne PRen legger inn Tailwind presetet vårt.
Jeg har fjernet alt som er deprecated og legacy. Kan diskuteres hvorvidt det som ligger igjen som custom components skal være med videre. Men kan kanskje se på det etter hvert?
Jeg har også endret slik at by default så lastes fontene fra https://www.obos.no. Før var Tailwind-configen satt opp slik at du var avhengig av å hoste fontene selv.

add package with Tailwind preset

---

.github/workflows/release.yml

Legger til v2 i release-workflowen

Add v2 branch to release-workflow

---

.changeset/rich-seals-scream.md
packages/react/src/TextField/TextField.tsx

Made label a ReactNode, this enables visual removal of the field while keeping the accessibility feature

Enabled custom label

---

.changeset/witty-camels-play.md
packages/react/src/StepList/StepList.tsx

Gjør det mulig legge inn `StepListItem` conditionally:
```
<StepList>
{false && (
<StepListItem bullet="test">Lorem</StepListItem>
)}
</StepList>
```

patch: Handle falsy child in StepList

---

package.json
packages/react/package.json
packages/react/src/Button/Button.tsx
packages/tailwind/package.json
pnpm-lock.yaml
prettier.config.js

Slik at de samme propertiene er på omtrentlig samme sted 😅

add prettier plugin for package.json

---

packages/react/package.json
packages/react/src/radiogroup/Radio.tsx
packages/react/src/radiogroup/RadioGroup.stories.tsx
packages/react/src/radiogroup/RadioGroup.tsx
packages/react/src/radiogroup/index.ts
packages/react/src/textfield/TextField.stories.tsx

Denne PR legger til initiell støtte for radio-knapper til Grunnmuren v2.
Merk at design ikke har sett på denne komponenten enda. Så det kommer nok endringer på både fokus, hover og selve radioknappen etter hvert.

 Initial commit of v2 Radio using react aria components

---

.changeset/funny-ghosts-shave.md
packages/react/src/Form/FormErrorMessage.tsx

We use the color from Grunnmuren v2: https://www.figma.com/file/9OvSg0ZXI5E1eQYi7AWiWn/Grunnmuren-2.0-%E2%94%82-Designsystem?node-id=251:1865&mode=dev
[AB#86847](https://dev.azure.com/obosbbl/95fe6e68-b1c5-4e8e-9ebb-fff9d8eeb377/_workitems/edit/86847)

FormErrorMessage: improve contrast

---

packages/react/src/checkbox/Checkbox.stories.tsx
packages/react/src/checkbox/Checkbox.tsx
packages/react/src/checkbox/CheckboxGroup.stories.tsx
packages/react/src/label/Description.tsx
packages/react/src/label/ErrorMessage.tsx
packages/react/src/label/Label.tsx

Add description and errormessage support to Checkbox. Flesh out storybook stories.

v2: Add description and errormessage support to Checkbox

---

.changeset/thin-books-allow.md
packages/react/src/checkbox/Checkbox.tsx
packages/react/src/radiogroup/Radio.tsx

the divs caused voiceover to read out empty groups in Chrome

fix screen reader issues with Checkbox and Radio

---

pnpm-lock.yaml

Gikk litt fort i svingene på merging-spree 🙃

 Fix broken pnpm-lock

---

form-demo/tailwind.config.cjs

Ellers så rendrer ikke eksemplet riktig

fix Tailwind content scan in form example

---

package.json
pnpm-lock.yaml

We got issues with formatting in vscode, downgrading worked

Downgrade prettier-plugin-packagejson

---

.changeset/calm-hounds-draw.md
packages/react/src/checkbox/Checkbox.tsx
packages/react/src/label/Description.tsx
packages/react/src/label/index.ts

Fjerner ekstra wrapper div fra Checkbox. Har ikke laget noe changeset her, føles ikke som en patch?

Replace Description with div to remove extra wrapper div

---

.github/workflows/main.yml
.github/workflows/release.yml
package.json
pnpm-lock.yaml

upgrade to pnpm v9

---

.changeset/happy-kiwis-shave.md
package.json
packages/react/package.json
pnpm-lock.yaml

https://react-spectrum.adobe.com/releases/2024-05-01.html

upgrade React aria dependencies

---

.changeset/curly-radios-jam.md
packages/tailwind/tailwind-base.cjs

Øker breakpoint fra `md` til `lg` for typografi

Fix breakpoints for typography

---

apps/docs/app.config.ts
apps/docs/app/app.css
apps/docs/app/routes/__root.tsx
apps/docs/package.json
apps/docs/postcss.config.js
apps/docs/tailwind.config.ts
apps/docs/tsconfig.json
pnpm-lock.yaml

Denne PRen konfigurerer opp Tailwind, postcss og Grunnmurens tailwind preset.
Siden rendres nå med OBOS fonten:

docs: add tailwind with Grunnmuren preset

---

apps/docs/app/routeTree.gen.ts
apps/docs/app/routes/ikoner.tsx
apps/docs/package.json
apps/docs/tailwind.config.ts
pnpm-lock.yaml

Denne PRen legger til et førsteutkast av en oversiktsside for ikoner.
Masse som mangler, men vil bare få inn ikoner og grunnmuren deps, før andre begynner å gjøre ting.

docs: add icon page

---

.changeset/config.json

Bruk package name, ikke path i changeset ignore 🤦‍♂️

Use package name in ignore

---

.changeset/config.json

Ignore full package name

---

apps/docs/app.config.ts
apps/docs/package.json
pnpm-lock.yaml

Så når jeg bygget doc siten at den bundlet Taiwansk locale 😅 
https://react-spectrum.adobe.com/react-aria/internationalization.html

docs: optimize bundle by removing unused RAC locales

---

.gitignore
apps/docs/.gitignore
apps/docs/README.md

Fixes gitignore pattern for docgen outputfile and adds documentation about the docgen script.

Fix gitignore and docs

---

.changeset/curvy-eagles-wonder.md
packages/react/src/content/content.tsx

Dette bør fikse https://obos.slack.com/archives/C03FR05FJ9F/p1733917726767389

fix type issue with refs for Heading and Content components

---

Dockerfile

Ser at npmrc blir mounta på et annet sted i grunnmuren docsen enn det gjør i våre andre apper. Tester å flytte den for å se om det funker for deploy

build: fix npmrc in Dockerfile

---

apps/docs/app/routes/studio/$.tsx
apps/docs/app/ui/footer.tsx

docs: minor fixes

---

apps/docs/app/routeTree.gen.ts
apps/docs/app/routes/_docs/index.tsx
apps/docs/app/routes/_docs/profil/farger.tsx
apps/docs/app/routes/_docs/profil/ikoner.tsx
apps/docs/app/routes/_docs/profil/index.tsx
apps/docs/app/ui/main-nav.tsx
apps/docs/package.json
pnpm-lock.yaml

Fixes the broken color docs page.

Fix color-docs

---

apps/docs/studio/documents/component.ts

Denna lägger till studio-support för länkar till gh/figma!

Add initial document links to figma/gh

---

.changeset/tasty-comics-leave.md

Glemte å inkludere icons-react i changesettet i stad, så her har det ikke blitt noen ny release....

add changelog for icons react

---

.github/workflows/release.yml

Ser om dette fikser den feilende release pipelinen

ci: add token to pnpm install in release pipeline

---

apps/docs/app/routes/_docs/komponenter/$slug.tsx
apps/docs/app/routes/_docs/profil/ikoner.tsx
apps/docs/app/ui/resource-links.tsx
apps/docs/sanity.types.ts
apps/docs/schema.json

Denne PRen legger til rendering av lenker til github/figma på komponent-siden.

docs: render resource links

---

.github/workflows/release.yml
package.json

ci: version script should only apply to packages

---

apps/docs/app/ui/component-preview.tsx

Adds `no-prose` to component preview

Add no-prose

---

.github/workflows/release.yml
package.json

ci: yet another attempt at fixing release pipeline

---

apps/docs/app/routes/_docs/komponenter/$slug.tsx
apps/docs/app/ui/anchor-heading.tsx
apps/docs/app/ui/content.tsx
apps/docs/app/ui/props-table.tsx

Denne PRen legger til støtte for anchor headings.

docs: add anchor headings

---

apps/docs/app/routes/_docs/komponenter/$slug.tsx
apps/docs/app/ui/content.tsx
apps/docs/app/ui/image-with-caption.tsx
apps/docs/studio/objects/content.ts
apps/docs/studio/objects/image-with-caption.ts
apps/docs/studio/schema-types.ts

Lägger till ett första utkast på bilder i portable-texten! La även til möjlighet för description
Hur borde vi hantera dimensionering? Nu bruker den bara w-full. Behöver vi mer begränsningar här, eller är vi good så länge vi laddar upp bilder med riktiga dimensioner?

Image with caption

---

apps/docs/app/routes/_docs/komponenter/$slug.tsx
apps/docs/sanity.types.ts
apps/docs/studio/documents/component.ts

This pull request introduces two updates to the components:
1. Reintroduces the `highlightAsNew` field with an added description to improve clarity and usage for marking new components.
2. Adds a new `documentationIsReady` boolean field, allowing users to indicate whether the documentation for a component is complete.
These changes aim to enhance usability and ensure comprehensive documentation for each component.

Add "highlightAsNew" and `documentationIsReady` fields to components

---

.changeset/large-waves-poke.md
packages/react/src/disclosure/disclosure.tsx

Adding support for `className` prop on `<Disclosure>`.

Support class name on disclosure

---

apps/docs/app/routes/_docs.tsx
apps/docs/app/routes/_docs/komponenter/$slug.tsx
apps/docs/app/routes/_docs/komponenter/index.tsx
apps/docs/app/routes/_docs/profil/index.tsx
apps/docs/app/ui/component-state-badge.tsx
apps/docs/app/ui/main-nav.tsx
apps/docs/sanity.cli.ts
apps/docs/sanity.config.ts
apps/docs/sanity.types.ts
apps/docs/schema.json
apps/docs/studio/documents/component.ts

The Pull Request introduces updates to the component documentation system, focusing primarily on enhancing metadata and refining the structure for better clarity and usability. It modifies query definitions, data structures, and schema attributes to improve consistency and extensibility.
- Updated query definitions and UI elements to introduce new fields: componentState (e.g., "in progress", "ready") and `documentationState` (e.g., "Docs are being written"). 
- Migrated from boolean `documentationIsReady` to a more descriptive state system for components and their documentation. 
- Introduced a new Sanity CLI configuration file (`sanity.cli.ts`) for project and dataset details. 
- Standardized string formatting in the Sanity schema types for better consistency. 
- Added new attributes to …

Improve component state management and consistency

---

.changeset/strong-singers-melt.md
packages/react/src/disclosure/disclosure.tsx

Make focus ring color work on any background - matches text color

Match focus color with text color

---

.changeset/new-jokes-fail.md
packages/react/src/card/card.tsx

Var glemt et sted til 😅 men usikker på hvordan fikse den delen hvor hover ikke funker på selve logoen? eller om det i det hele tatt skal være, skjer ikke hvis du hovrer over badgen heller så muligens "by design"
https://github.com/user-attachments/assets/44ce1291-1fdd-4f1a-aa19-525f006c0309

fix hover on extra imgs in cards

---

packages/react/src/index.ts
packages/react/src/modal/index.tsx

Exposes modal in the react package..... 🤦

Expose modal

---

packages/react/src/file-upload/file-upload.stories.tsx
packages/react/src/file-upload/file-upload.tsx

Export props type

---

packages/react/src/index.ts

Export Tags

---

apps/docs/app/ui/main-nav.tsx

docs: add logo to menu

---

.changeset/red-maps-cry.md
packages/react/src/file-upload/file-upload.tsx

Fixes a rendering bug for custom error message in `FileUpload`

Fix error message rendering bug

---

.changeset/free-nails-attack.md
.changeset/sharp-flies-vanish.md
packages/react/src/disclosure/disclosure.tsx

Fixes two major issues in the `Disclosure` component:
1. Nested `<Disclosure>` components not working (at all)
2. Support dynamic children based on the `<Disclosure>` state by also accepting children as a callback function.

Fix Disclosure

---

apps/docs/app/routes/__root.tsx
apps/docs/package.json
pnpm-lock.yaml

Denne PRen legger [@tanstack/router-devtools](https://tanstack.com/router/latest/docs/framework/react/devtools).
Devtools viser deg hvilke routes som er aktive, router params, data som er lastet som en del av routen etc.
Devtools er bare tilgjengelig i dev mode.
Closed:
Expanded:

docs: add router-devtools

---

apps/docs/app/ui/main-nav.tsx

Den var lite tight innan. Detta ger mer luft!

add spacing to hr

---

packages/react/src/video-loop/video-loop.tsx

Fixes a small typo in the VideoLoop props docs

Fix props docs

---

.changeset/pre.json

Exit the pre release mode for changesets

Exit pre release mode

---

.changeset/metal-bats-sit.md
packages/tailwind/package.json

Testa litt hos oss i dkt-medlem og ser ut som noen filer mangler i bundlene til tailwind-pakka

Tailwind: export all files needed for the consumer

---

.changeset/poor-kings-bow.md
packages/react/src/card/card.tsx
packages/tailwind/package.json
packages/tailwind/tailwind-base.css
pnpm-lock.yaml

Remove unused `tailwind` deps and replace [tailwindcss-animate](https://github.com/jamiebuilds/tailwindcss-animate) with [tw-animate-css](https://github.com/Wombosvideo/tw-animate-css)

Remove unused tailwind deps

---

Dockerfile

Resurserna verkar inte finnas, så vi testar att kopiera content i public till bundlen

test copying public

---

Dockerfile
apps/docs/package.json

Siden den inte verkar få det genom byggsteget, ska jag prova att kopiera det direkt i dockerfilen fra nodemodules

Try copying icons explicitly

---

.changeset/dull-cougars-learn.md
packages/react/src/avatar/avatar.stories.tsx
packages/react/src/avatar/avatar.tsx
packages/react/src/card/card.stories.tsx

Unflag `Avatar` as unsafe, it is stable

Flag as stable

---

.changeset/thick-clouds-agree.md
packages/react/src/hero/hero.tsx

Makes sure that headings are auto hyphenated across browsers for the Hero component

Auto hyphens in hero

---

.changeset/swift-cases-care.md
packages/react/src/accordion/accordion.tsx

Change font-weight from semibold to medium in `<Accordion>`

Update accordion font weight

---

apps/docs/src/ui/scroll-to-top.tsx

Fix til tops

---

.changeset/two-lights-jump.md
packages/react/src/card/card.tsx

Accept all HTML props for the `<Card>` component

Allow html props for card

---

.changeset/public-showers-read.md
packages/react/src/link-list/link-list.tsx

Fix prop passing for the `LinkList` component

Fix rest props passing for link list
