code-obos/grunnmuren

- .eslintrc.json
- .github/workflows/main.yml
- package.json
- pnpm-lock.yaml
Add and configure eslint. Run it during CI.
The eslint config includes React linting, even though we don't have any React in the repository yet. Since we know that this repo will include React components in the future, we might as well copy it over from our internal repo right away.
Edit:
CI fails because we don't have any JS to lint yet. Won't merge this until we do, so we know it runs correctly.
> add eslint to CI

- .changeset/smooth-eyes-scream.md
- .github/workflows/main.yml
- package.json
- packages/icons/.gitignore
- packages/icons/README.md
- packages/icons/index.cjs
- packages/icons/index.mjs
- packages/icons/package.json
- packages/icons/scripts/figma-import.mjs
- packages/icons/scripts/make-react-icons.mjs
- packages/icons/scripts/optimize.mjs
- packages/icons/scripts/utils.mjs
- packages/icons/tsconfig.json
- packages/icons/vite.config.js
- pnpm-lock.yaml
- tsconfig.json
This PR adds tooling to convert the SVG icons into React components.
A script that uses [svgr](https://react-svgr.com/) transforms the SVGs into React components. These are all written to a gitignored file, before bundling through [vite](https://vitejs.dev/) and TS. That means the React components aren't checked into this repo. They are generated as part of the build step.
For accessibility reasons, the icons are rendered with `role="img"`. If an `aria-label` isn't provided, the icons automatically sets `aria-hidden`. This is the most common use case, as icons should be used for decorative purposes only.
Note that this only applies to the React components, not the SVGs.
* Removed the default export. It was undocumented, and the only thing it did was exporting a path to the folder with the …
> add React components version of icons

- .changeset/khaki-jars-retire.md
- packages/icons/README.md
- packages/icons/package.json
use default export for React icons instead of subpath export `/react`.
TS doesn't support type declaration for subpath exports (coming in version 4.7, which is currently in beta)
> use default export for React icons

- .changeset/hip-singers-nail.md
- packages/react/src/Banner/Banner.tsx
- packages/tailwind/tailwind-base.cjs
The prose width was defined with the character width unit. The new font is smaller than the old one, so with the new font the maximum text width was suddenly 427px instead of 590px.
I also fixed the banner component. It should use the regular container instead of being centered. It was simply me who had misunderstood the design sketches.
> Banner fixes

- .changeset/eleven-apricots-wave.md
- packages/react/src/Typography/stories/Typography.stories.tsx
- packages/tailwind/tailwind-base.cjs
Update the prose component class so unordered lists looks more like the [design sketches](https://www.figma.com/file/XRHRRytz9DqrDkWpE4IKVB/OBOS-DS?node-id=1%3A362)
The bullet point size and spacing needs to be adjusted some more to look like the design, but that requires some more work than simply changing the color and margin for the list items. Baby steps etc.
> match unordered lists more closely to design

- .changeset/quick-walls-taste.md
- packages/react/src/TextArea/TextArea.tsx
- packages/react/src/TextField/TextField.tsx
- packages/react/src/hooks/useFormControlValidity.ts
The browser built in validation has some problems:
- It renders differently in every browser.
- It only renders for a single field at a time.
- It often renders using a tooltip.
We want to render the error messages with our own design. In theory it could be done by using fully controlled inputs, and then checking everything yourself, but we would rather take advantage of the [constraint validation API](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Constraint_validation) and the browser built ins.
This PR adds support for "extracting" the error message from the [`invalid`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/invalid_event) event, then render it using our own error component. This is what it looks like: …
> feat: automatic validation using validation constraint API

- .changeset/tame-foxes-smash.md
- packages/tailwind/README.md
- packages/tailwind/tailwind-base.cjs
With this the consuming application can host the fonts on a different
path than `/fonts`. We still assume the font file names.
> Tailwind: allow specifying font base path

- .changeset/tricky-doors-fetch.md
- packages/react/src/Input/Input.tsx
specifying a differnt type, such as `type="email"` still resulted in the
type being set to the default `text`
> bug: override type attribute in TextField

- .changeset/sixty-plants-learn.md
- packages/react/package.json
- pnpm-lock.yaml
because we need to specify a version range of grunnnmuren-tailwind that we're compatible with, but we don't really import anything from it, so make it optional.
> move grunnnmuren-tailwind to an optional peer dependency

- .changeset/lovely-bulldogs-attack.md
- packages/tailwind/tailwind-base.cjs
- pnpm-lock.yaml
Add option for users to change containersize to 80rem instead of 90rem. 
80rem is the legacy width size of a container.
> Tailwind:  Configuration option for legacy container size

- packages/react/tailwind.config.cjs
The storybook on GH pages is hosted https://code-obos.github.io/grunnmuren/, so we need to include `grunnmuren` in the base path for the fonts to load correctly.
> fix font path for GH pages

- .changeset/itchy-goats-fix.md
- packages/tailwind/tailwind-base.cjs
We have to add 2rem to the container and container-prose classes because we also use 1rem padding on both left and right side, this means that the container is actually 32px smaller than it should be.
1440px width:
1280px width:
container-prose:
> tailwind: add 2rem to container/container-prose

- .changeset/early-shrimps-pretend.md
- .changeset/six-seahorses-compete.md
- packages/react/src/Card/CardLinkOverlay.tsx
* Add support for `className` prop to CardLinkOverlay.
* Remove unecessary class `before:content-['']`. All of Tailwind's classes with the `before:` modifier sets this automatically.
> Add className forwarding to CardLinkOverlay

- .changeset/silver-singers-swim.md
- packages/react/src/Checkbox/Checkbox.tsx
When using Checkbox along with a text that wraps, the checkbox is squeezed so that the shape looks weird. This PR adds a flex-none class to the input in order no avoid this squeeze.
Example of previous behavior:
I also know that the nærkontor-team has encountered this problem.
> Add flex-none to Checkbox to avoid shape-squeeze

- .changeset/curvy-rockets-invent.md
- packages/react/src/Campaign/Campaign.tsx
- packages/react/src/Campaign/index.ts
- packages/react/src/Campaign/stories/Campaign.stories.tsx
- packages/react/src/index.ts
This PR implements the [Campaign component from Figma](https://www.figma.com/file/XRHRRytz9DqrDkWpE4IKVB/OBOS-DS?node-id=571%3A9357)
It is used as this:
```jsx
<Campaign>
<Campaign.Image src="..." />
<Campaign.Body>
Lorem ipsum
</Campaign.Body>
</Campaign>
```
The image component supports a prop `rightAlign`, that uses the [CSS order property](https://developer.mozilla.org/en-US/docs/Web/CSS/order) to move the image to the right.
Even though `order` is kind of frowned upon, I think it's okay in this case since it's not the default, an image isn't tabbable and it only happens on desktop. The use case here is to support alternating the image on the left/right side of the content when multiple campaigns are rendered in succession (see Figma).
The image component also supports custom …
> add Campaign component

- .changeset/orange-laws-promise.md
- packages/react/src/Radio/Radio.tsx
- packages/react/src/Radio/RadioContext.tsx
- packages/react/src/Radio/RadioGroup.tsx
- packages/react/src/Radio/index.ts
- packages/react/src/Radio/stories/Radio.stories.tsx
- packages/react/src/index.ts
- packages/tailwind/tailwind-base.cjs
This PR implements Radio group buttons.
It is implemented following this guide: https://moderncss.dev/pure-css-custom-styled-radio-buttons/
The figma spec can be found [here](https://www.figma.com/file/XRHRRytz9DqrDkWpE4IKVB/OBOS-DS?node-id=2815%3A42817).
The component supports both controlled and uncontrolled mode, and label/help text. Note that an invalid state is not yet implemented.
> add radio buttons

- renovate.json
Add renovate configuration to group all svgr packages in the same PR, to prevent this:
See [renovate docs for package rules](https://docs.renovatebot.com/configuration-options/#packagerules)
> renovatebot: group all @svgr packages

- renovate.json
add renovate config to group together vite packages to prevent this:
> renovatebot: group all vite packages

- .changeset/spotty-jokes-call.md
- packages/react/src/Button/Button.tsx
- packages/tailwind/tailwind-base.cjs
Denne PRen flytter over større deler av Button sin styling fra Tailwind utilities til en Tailwind component. Det gjør det enklere dersom du har tilfeller der du må overstyre default stylingen. For å få til dette før denne PRen måtte du bruke important modifieren.
Før:
```jsx
<Button className="!absolute top-0 left-0" />
```
Etter:
```jsx
<Button className="absolute top-0 left-0" />
```
> refactor: button as Tailwind component

- packages/react/package.json
- packages/react/src/Card/stories/Card.stories.tsx
- packages/react/src/Hero/stories/Hero.stories.tsx
- packages/react/src/Input/stories/Input.stories.tsx
- packages/react/tsconfig.json
- pnpm-lock.yaml
Improves editor experience by no longer excluding Storybook stories in the tsconfig. This has the additional benefit that TS errors in the stories also breaks CI.
However, that meant that the TS type declaration script generates typings for all the story files, which we don't want, so we remove them again using rimraf.
> include typescript for stories and remove their type declarations

- .changeset/nasty-cars-run.md
- packages/react/src/Button/Button.tsx
- packages/react/src/Button/stories/Button.stories.tsx
- packages/tailwind/tailwind-base.cjs
- pnpm-lock.yaml
Denne PRen legger til en `loading` prop på Button komponenten.
https://user-images.githubusercontent.com/81577/185920449-2614ce64-068e-4e8e-a731-29e166d1991d.mp4
For å indikere loading state til skjermlesere har jeg brukt `aria-busy`, da ser at Entur har løst det på den måten: https://design.entur.org/komponenter/knapper/button
Dessverre er resten av implementasjonen litt meh... Vi vil ikke at knappen skal endre størrelse når man hopper mellom loading state og ikke, så knappens innhold må alltid "rendres". Dette er også mest skjermleservennlig.
Problemet er at noen av knappene har transparante bakgrunner. Det betyr at loading overlayet også må være transparent,  og da vil det i enkelte tilfeller være slik at man ikke kan skjule knappens innhold bak loading overlayet:
For å fikse det, …
> feat: add loading modifier to Button component

- packages/react/src/Accordion/Accordion.tsx
without this property, the right side of the accordion header isn't rounded:
> Accordion: add `overflow-hidden` for the rounded corners to work

- .changeset/tough-humans-smoke.md
- packages/react/src/Hero/HeroContent.tsx
- packages/react/src/Hero/HeroImage.tsx
Update the hero image after adjustments in Figma.
The images does no longer have round corners. Also updated the "vertical-split" layout to match Figma.
> Hero image changes

- .changeset/red-ladybugs-collect.md
- packages/react/src/Footer/Footer.tsx
- packages/react/src/Hero/stories/Hero.stories.tsx
- packages/react/src/Navbar/Navbar.tsx
- packages/react/src/PageLayout/stories/PageLayout.stories.tsx
- packages/tailwind/tailwind-base.cjs
Denne endringen fikser litt på hvordan vi bygger opp sidelayouten med footer og navbar. Tidligere måtte man passe på å bruke riktig utility klasser selv for å få til layouten vi ønsker.
Ny måte blir nå:
```jsx
<body class="page-layout">
<Navbar />
<main className="page-layout-main">
<h1>Hello world</h1>
<Footer />
</body>
```
Fant også ut at med litt triksing så kan man bygge inn de hvite kurvene rett i navbar og footer med pseudoelementer. Dette gjør at vi slipper å styre med border radius på main contentet, så bruke negative marginer til å pushe det innholdet inn i footer/navbar.
> new layout components. moved curved corners to footer and navbar

- .changeset/stupid-eagles-nail.md
- packages/react/src/Form/FormLabel.tsx
- packages/react/src/Hero/HeroImage.tsx
- packages/react/src/Input/Input.tsx
- packages/react/src/Input/stories/Input.stories.tsx
- packages/react/src/TextArea/TextArea.tsx
- packages/react/src/TextField/TextField.tsx
Changes done to Input, FormLabel, TextField and TextArea. 
Har testa endringene lokalt i medlemsteamet hvor vi legger til en country code select som prefix, og det funker fortsatt likt som tidligere
Input:
- Added suffix
- Added prefix
- dark blue color on focues border
- black border unfocused
- Small padding change to be more aligned with figma
Textfield: 
- Added prefix/suffix
- Send inValid prop to FormLabel
- Moved description between input and label
TextArea:
- Send inValid prop to FormLabel
- Moved description between input and label
Formlabel:
- Move required-char to front of label
- Change color on required-char if invalid or not
- semibold label
> Changes: Input/Textfield/TextArea

- packages/react/src/Navbar/NavbarExpandedMobileContent.tsx
- packages/react/src/hooks/useScreenMaxWidthMd.ts
`useMedia` from react-use requires a default state, otherwise it logs console messages during SSR
> fix SSR warning for useMedia hook

- .changeset/shy-dots-grow.md
- packages/react/src/Footer/Footer.tsx
> fix footer rendering artifact issue

- .changeset/pink-items-leave.md
- packages/react/src/StepList/StepList.tsx
The content of the StepListItem's bullet point is supposed to be centered. If you rendered it with a custom image, that wasn't the case...
Before this change:
After this change:
> ensure StepListItem's bullet content is centered

- .changeset/late-experts-begin.md
- packages/react/src/__stories__/Typography.stories.tsx
- packages/tailwind/tailwind-base.cjs
Hadde denne liggende i en branch fra da jeg implementere QuoteBlock i appen. Kan like gjerne få den inn her.
Merk at denne kanskje ikke følger DS helt, da quotes der er mer ment som en CMS-blokk, ikke som en del av tekst som brukt her.
Før:
Etter:
> use OBOS colors for blockquotes in prose class

- .changeset/tidy-rivers-fail.md
- packages/react/src/Checkbox/Checkbox.tsx
- packages/react/src/Checkbox/stories/Checkbox.stories.tsx
- packages/react/src/Input/Input.tsx
- packages/react/src/TextArea/TextArea.tsx
- packages/react/src/TextField/TextField.tsx
- packages/react/src/TextField/stories/TextField.stories.tsx
- packages/react/src/hooks/useFormControlValidity.ts
- packages/react/src/utils/index.ts
~~Endringen her gjør at label for TextField og TextArea komponentene viser "Påkrevd asterix" uansett om påkrevdhet er satt via `required` eller `aria-required`. Intensjonen er å enkleregjøre custom validering av påkrevde felter.~~
~~Usikker på om dette er beste måten å løse det på... Andre mulige alternativer som muligens kan oppnå det samme.~~
* ~~Benytte [`novalidate`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#attr-novalidate) på formet.~~
* ~~I stedet for at komponenten støtter både required og aria-required slår vi den sammen til en prop `isRequired?: boolean | 'sr-only';`.. Kanskje noe for v2 uansett?~~
* ~~At komponenten automatisk overfører `required` til `aria-required` når du setter `validate={false}` på komponenten.~~
Stryk forrige. Har tenkt litt mer på …
> Better support for custom validation in `<TextField>` and `<TextArea>`

- .changeset/fair-beds-push.md
- packages/react/src/Checkbox/Checkbox.tsx
- packages/react/src/TextArea/TextArea.tsx
- packages/react/src/TextField/TextField.tsx
even if the form control didn't have an error or description associated with it, the resulting HTML was `aria-describedby=""`, which breaks accessibility.
Side note: we should really look into extracting some of the common stuff to helper instead of repeating for each form control type -.-
> fix: aria-describedby was always set for form components

- .changeset/twelve-zebras-relate.md
- packages/react/src/Accordion/Accordion.tsx
- packages/react/src/Card/Card.tsx
- packages/react/src/StepList/StepList.tsx
- packages/tailwind/tailwind-base.cjs
Oppdaget ved en tilfeldighet at man kan sette en default border color. Setter denne til light gray, så det matcher design systemet https://www.figma.com/file/XRHRRytz9DqrDkWpE4IKVB/OBOS-DS?node-id=1%3A228
Vi hadde også feil gråfarge på Accordionen...
> set light gray as the default border color

- .changeset/small-timers-pump.md
- packages/react/src/Accordion/Accordion.tsx
This is probably a micro optimization, but with [Tailwind 3.2](https://tailwindcss.com/blog/tailwindcss-v3-2#aria-attribute-variants) we can use the ARIA variants instead of cslx to apply the appropriate classes
> refact: use tw ARIA variants in Accordion

- .changeset/sharp-geckos-try.md
- packages/react/package.json
- packages/react/src/Pagination/Pagination.tsx
- packages/react/src/Pagination/index.ts
- packages/react/src/Pagination/stories/Pagination.stories.tsx
- packages/react/src/index.ts
- pnpm-lock.yaml
Denne PRen legger til en pagineringskomponent.
Det er en litt mer polert versjon av den som benyttes nederst her https://nye.obos.no/boligforvaltning/tips-og-rad/.
[Figma spec](https://www.figma.com/file/XRHRRytz9DqrDkWpE4IKVB/OBOS-DS?node-id=777%3A10087&t=K4bNyvVmARPA0Bbz-0)
Video demo:
https://user-images.githubusercontent.com/81577/204568974-2a68f43d-afcd-4ec0-986b-c595b27ca6d7.mp4
Jeg har lagt til [type-fest](https://github.com/sindresorhus/type-fest), er egentlig ikke fan fordi typesignaturene den genererer er ofte veldig vanskelige å forstå... Men dersom du har flere nav-elementer på en side må du gi dem labels for at en skjermleser skal kunne skille på dem. Jeg har brukt type-fest til å sikre at du enten spesifiser `aria-label` eller `aria-labelledby` for pagineringen.
> add Pagination component

- .changeset/hip-hounds-wait.md
- packages/react/src/StepList/StepList.tsx
- packages/react/src/StepList/stories/StepList.stories.tsx
Denne PRen legger til støtte for at man selv kan velge alignment av sirklene i StepList-komponenten. Enten `top` eller `center`.  Dersom man har lengre tekster ser `top` bedre ut, mens `center` blir bedre for korte...
```tsx
// default for backwards compatibility
<StepList align="center" />
<StepList align="top" />
```
- Bruk flex og gap i StepList
- Fikser også en bug hvor strekene var off dersom det var lengre tekster for hvert item
> StepList: support top and center alignment for bullet items

- .changeset/lazy-cooks-melt.md
- .changeset/orange-avocados-enjoy.md
- packages/react/src/Checkbox/Checkbox.tsx
- packages/react/src/Radio/Radio.tsx
- packages/tailwind/tailwind-base.cjs
Følger samme som checkboxes. Siden vi ikke har bestemt om det skal være top-aligned eller center-aligned så følger vi bare samme som checkbox i første omgang
> Checkbox/Radio: Improve alignment for multiline labels

- .changeset/seven-chicken-type.md
- packages/react/src/Radio/Radio.tsx
- packages/react/src/Radio/RadioContext.tsx
- packages/react/src/Radio/RadioGroup.tsx
- packages/react/src/Radio/stories/Radio.stories.tsx
- RadioGroup-komponenten støtter en `error` prop som rendrer en feilmelding hvis en av alternativene ikke er valgt
- Hjelpetekst/beskrivelse er flyttet til før radio-knappene
https://www.figma.com/file/XRHRRytz9DqrDkWpE4IKVB/OBOS-DS?node-id=1198%3A11466&t=Lhq1VWRdKLW3ltef-0
[AB#65940](https://dev.azure.com/obosbbl/Content%20hub/_boards/board/t/Team%20Nettsted%20og%20B2B/Stories/?workitem=65940)
> Added support for error props and moved description for RadioGroup

- .changeset/modern-turkeys-sing.md
- packages/react/src/Campaign/Campaign.tsx
- packages/react/src/Card/Card.tsx
- packages/react/src/Card/CardContent.tsx
- packages/react/src/Card/CardImage.tsx
- packages/react/src/Card/CardList.tsx
Legger til forwardRef på Campaign og Card kompontener. 
> Fortsatt en siste bug med generiske komponenter. Campaign funker ikke helt som det skal
EDIT: gjelder ikke lenger, se kommentarer. 
Minor eller bare patch? Endrer sånn set ikke noe for brukeren, men legger til ny funksjonalitet så kanskje en minor?
> add forwardRef to campaign and card components

- .changeset/real-cows-tie.md
- packages/react/vite.config.js
Denne PRen forsøker å gjøre Grunnmuren enklere å ta i bruk med React server components / Next.js 13 app directory.
Siden vi bundler hele grunnmuren ned til én fil holder det at vi får inn et `'use client';` directive i toppen av den fila, så det er det endringen i denne PRen gjør.
Det gjør at hele react-grunnmuren blir client components, men det gjorde de jo strengt tatt før det var noe som het RSC også... Det er en del komponenter som ikke bruker client side effects som i teorien kunne vært RSC-er, men det ville krevd en omstrukturering av hele libbet, så det får vente til en ny major versjon.
For nå gjør disse endringen at alle som vil teste RSC med grunnmuren slipper å wrappe dem i egne client components (som beskrevet her https://beta.nextjs.org/docs/rendering/server-and-client-compone …
> feat: add `'use client';` directive for better RSC interop

- .changeset/rude-parrots-report.md
- packages/react/src/Banner/Banner.tsx
- packages/react/src/Banner/BannerImage.tsx
Banner tweaks from Hanne:
* Place content of banner in center
* Smaller icon and heading.
* Align icon center on mobile.
> Place content of banner in center.

- .changeset/serious-actors-drum.md
- package.json
- packages/tailwind/tailwind-base.cjs
trodde jeg kunne legge til `md` i configen til typography men da gjaldt det tydeligvis bare `prose-md` håndteringen. Så da ble det slik hentet fra https://github.com/tailwindlabs/tailwindcss/discussions/3060
> tailwind: headings follow styleguide when using prose

- .changeset/curly-walls-clap.md
- packages/react/.storybook/main.js
- packages/react/src/Banner/stories/Banner.stories.tsx
- packages/react/src/Button/Button.tsx
- packages/react/src/Button/stories/Button.stories.tsx
- packages/react/src/Chip/Chip.tsx
- packages/react/src/Chip/stories/Chip.stories.tsx
- packages/react/src/Form/FormSuccess.tsx
- packages/react/src/Hero/Hero.tsx
- packages/react/src/Pagination/Pagination.tsx
- packages/react/src/hooks/useBlockBackgroundColor.ts
- packages/tailwind/tailwind-base.cjs
Add new colors mint and sky. Old colors are deprecated
`blue-light` -> `sky`
`blue-lightest` -> `sky-light`
`green-light` -> `mint`
`green-lightest` -> `mint-light`
`gray-concrete` -> `gray-lightest`
`<Button>` has a new Color-prop `mint` which is the same as `light-green`.
`<Chip>` has a new Color-props `mint` and `sky` which are the same as `green-light` and `blue-light` respectively.
`<CardList> | <Banner>` have new Color-props `mint` and `sky` which are the same as `green` and `blue` respectively
> Tailwind new colors

- .changeset/metal-months-cover.md
- packages/react/package.json
- packages/react/src/Accordion/Accordion.tsx
- pnpm-lock.yaml
Upgrade [react-collapsed dependency](https://github.com/roginfarrer/collapsed).
* It no longer uses a default export
* [It sets `role="region"` for the collapsible panel now,](https://github.com/roginfarrer/collapsed/releases/tag/%40collapsed%2Freact%404.0.0) so we no longer need to do it ourselves
* [it actually checks if the user prefers reduced motion internally](https://github.com/roginfarrer/collapsed/blob/3a84a2a8ce2fd6f9ecab32eef447c4e61c6c8e2d/packages/react-collapsed/src/index.ts#L89), so we don't need to do it ourselves
According to the release notes, it should also handle setting aria-labelledby for the collapsibe panel, but I couldn't get that to work, so therefore we keep setting that ourselves.
> upgrade react-collapsed dependency

- .changeset/twenty-starfishes-marry.md
- packages/react/src/Form/FormLabel.tsx
- packages/react/src/Form/MultiStep/FormStep.tsx
- packages/react/src/Form/MultiStep/FormStepContext.tsx
- packages/react/src/Form/MultiStep/FormStepHeader.tsx
- packages/react/src/Form/MultiStep/index.ts
- packages/react/src/Form/index.ts
- packages/react/src/Form/stories/Form.stories.tsx
Endringer
- Fjernet aria-hidden på *
- header er alltid button, men disabled hvis formStatus !== completed og den er Collapsed
- FormStep Counter er inne i header, samme er description (ikke utfylt, completed osv)
- Fokus på neste steg etter at man har trykka på neste (fokus skal på button, og ikke på første input)
I teorien så har jeg nå lagt til prelease mode i changeset i `next`-branchen. Denne merges inn til next-branchen og så lages det en beta-release som vi kan teste med. Har ikke fått testa dette, så blir spennende når det blir merga inn
> Feature: FormStep

- .changeset/quiet-pigs-look.md
- packages/react/src/Form/MultiStep/FormStepContext.tsx
Kanskje litt overkill?
useFormContext som returnerer
- formData
- activeStep
useFormStepContext returnerer i tillegg
- nextFormStep (bare går videre til neste)
- setFormData (setter formdata for steget)
> formStep: export more states from formStepContext

- .prettierrc.cjs
as it was fixed in Prettier v3. See https://github.com/prettier/prettier/issues/8056
This would also allow us to convert the config file to JSON or ESM if we want to.
> remove no longer needed prettier plugin loading workaround

- .changeset/poor-cycles-pretend.md
- packages/react/src/Campaign/Campaign.tsx
Siden det ikke er lov å bruke dot-notasjon på klient komponenter i RSC, så er en midlertidig løsning å eksponere alle komponentene sånn at vi kan bruke `<CampaignBody>,<CampaignImage>` hver for seg i stedet for `<Campaign.Body>, <Campaign.Image>`
> Export all campaign components and types

- .changeset/short-eggs-shave.md
- packages/react/src/Hero/HeroImage.tsx
Layout og aspect-ratio på hero-bilde endres ved 640 px bredde, mens URL-en ble endret ved 768 px bredde. Fikset slik at URL-en også byttes ved 640 px bredde.
> Endret min-width for når stort bilde brukes

- .changeset/happy-socks-pay.md
- packages/react/package.json
Denne PRen fikser på package.json exports slik at Grunnmuren kan brukes i TS prosjekter som har[ moduleresolution](https://www.typescriptlang.org/tsconfig#moduleResolution) satt til `Bundler`.
Nye Next-prosjekter i TS setter `Bundler` by default, så greit at dette er på plass.
Før:
Etter:
For Node16 får vi en [`Internal resolution error` ](https://github.com/arethetypeswrong/arethetypeswrong.github.io/blob/main/docs/problems/InternalResolutionError.md) når jeg jeg sjekker package.json med [arethetypeswrong.io](https://github.com/arethetypeswrong/arethetypeswrong.github.io). I dokumentasjonen ser det ut til at det kan oppstå når man har bundlet og generert typene med forskjellige verktøy (noe vi gjør for denne pakken), men at bare kan være et potensielt problem for folk som ikke har …
> fix: add support for moduleResolution Bundler

- .changeset/big-lions-rule.md
- packages/react/package.json
I https://github.com/code-obos/grunnmuren/pull/586 forsøkte jeg å legge til støtte for TS' `"moduleResolution": "Bundler"`. Dette er default oppsettet for blant annet Next.js prosjekter i TS nå, så det gir mening at vi støtter dette i grunnmuren.
Det jeg ikke la merke til i den PRen er at siden jeg slang inn `type: module` i package.json, så endret plutselig vite på filendingen når den spyttet ut den bundlede filen. Da gikk den fra `.mjs` til `.js`.
```sh
> vite build
vite v4.4.9 building for production...
✓ 81 modules transformed.
dist/grunnmuren.js
> vite build
vite v4.4.9 building for production...
✓ 81 modules transformed.
dist/grunnmuren.mjs 
```
Dette knakk dermed pakken, for som man ser av exports feltet i package.json så peker den på `./dist/grunnmuren.mjs`, ikke …
> fix: package was broken because of wrong file extension

- packages/react/src/Button/Button.tsx
- packages/react/src/utils/useClientLayoutEffect.ts
Denne PRen legger den bruker nå samme teknikk som NAV for å beholde bredden på knappen https://github.com/navikt/aksel/blob/main/%40navikt/core/react/src/button/Button.tsx, i stedet for den litt mer komplekse måten vi løste det på før https://github.com/code-obos/grunnmuren/blob/6cddc29ae9d37c486be954e35920710c0dde4bb6/packages/react/src/Button/Button.tsx#L96
> add loading spinner to Button

- README.md
Siden vi deployer storybooken til Netlify er det greit med en badge som viser statusen på deploy tenker jeg. READMEn trenger ganske mye mer utfylling, men tar ikke det som en del av denne tasken.
Docs for badge: https://docs.netlify.com/monitor-sites/status-badges/
> add deploy status badge to README

- packages/react/src/label/Label.tsx
- packages/react/src/radiogroup/RadioGroup.tsx
- packages/react/src/textfield/TextField.tsx
Update label after latest design changes. Most notable change is that the required asterix has been dropped.
https://www.figma.com/file/9OvSg0ZXI5E1eQYi7AWiWn/Grunnmuren-2.0-%E2%94%82-Designsystem?node-id=353%3A4676&mode=dev
> v2 label design changes

- packages/react/src/label/Description.tsx
- packages/react/src/label/ErrorMessage.tsx
- packages/tailwind/tailwind-base.cjs
Adjust error message and description after [design changes in Figma](https://www.figma.com/file/9OvSg0ZXI5E1eQYi7AWiWn/Grunnmuren-2.0-%E2%94%82-Designsystem?node-id=407%3A5976&mode=dev)
The reds are updated for improved contrast and accessibility. In addition the icon has been removed from the error message.
> v2 error message and description design changes

- packages/react/src/radiogroup/Radio.tsx
- packages/react/src/radiogroup/RadioGroup.stories.tsx
Oppdaterer radio buttons etter at det er kommet [skisser på de i Figma](https://www.figma.com/file/9OvSg0ZXI5E1eQYi7AWiWn/Grunnmuren-2.0-%E2%94%82-Designsystem?node-id=397%3A5389&mode=dev)
Klikkflaten er større, slik som gjort i Checkbox-PRen for bedre UU.
Det som gjenstår nå er hover state, men det mangler i Figma..
> adjust radio group after design changes

- packages/tailwind/README.md
- packages/tailwind/package.json
- packages/tailwind/tailwind-base.cjs
- pnpm-lock.yaml
Denne PRen legger til støtte for å kjøre versjon 2 av presetet i en slags v1 kompabilitetsmodus. Dette enables ved å kjøre presetet med følgende options:
```js
// tailwind.config.js
/** @type {import('tailwindcss').Config} */
module.exports = {
presets: [
require('@obosbbl/grunnmuren-tailwind')({ legacyV1Compatibility: true }),
],
};
```
Det betyr ikke full bakoverkompabilitet, men den er god nok til at versjon 2 av presetet kan kjøres sammen med versjon 1 av React komponentene. Dette lar deg ta i bruk v2 uten at du nødvendigvis må gjøre en full migrering fra v1 til v2, men heller kan gjøre det over tid.
~~gjør vi med aspect-ratio pluginet? Skal vi bare legge det til i kompabilitetsmodus, eller skal det være enabled by default? Her må vi se på browserstatistikk og hvilke browsere vi …
> Compatibility support for v1 in v2 Tailwind preset

- packages/react/src/button/Button.tsx
Fixes link (anchor) buttons being rendered with underlines.
Before:
After:
> v2: prevent underline for button links

- packages/tailwind/tailwind-base.cjs
I v1 av Tailwind-presetet _extendet_ vi fargene til Tailwind med OBOS sin fargepalett. Det fungerte greit nok, men det gjorde at man fikk opp haugevis med grønnfarger på autocomplete (som ikke er en del av fargepalett).
I V2 _overskriver_ vi derfor heller Tailwind sine farger med OBOS sine. Men da forsvant samtidig noen utility farger som transparent, currentColor og inherit.
Denne PRen legger de inn så man man fortsatt kan bruke disse, for eksempel som bakgrunn:
> add back special colors like transparent to color theme

- .storybook/main.js
- package.json
- packages/react/src/radiogroup/Radio.tsx
- packages/react/src/radiogroup/RadioGroup.stories.tsx
- packages/react/src/radiogroup/RadioGroup.tsx
- pnpm-lock.yaml
TLDR:
- Hover state for radioknapp
- Storybook actions plugin
- Masse nye stories for RadioGroup.
PRen legger til hover state for radioknapper:
https://github.com/code-obos/grunnmuren/assets/81577/120ac6b8-a86e-4638-aa95-51b8edc263b2
Den legger også til betydelig flere stories for radiogruppen. Da har vi mer eksplisitte stories i stedet for at man må sitte og klikke av og på varianter via storybook kontroll-panelet:
Den legger også til [Storybook actions pluginet](https://storybook.js.org/docs/react/essentials/actions), slik at vi kan logge event handlers i storybooken:
> Add hover state and stories to RadioGroup

- packages/react/src/checkbox/CheckboxGroup.stories.tsx
- packages/react/src/checkbox/CheckboxGroup.tsx
Denne PRen gjør egentlig mye av det samme som i #625. Den legger til fler og mer eksplisitte stories for CheckboxGroup.
Fikser også en liten bug hvor tomt label ble rendret dersom det ikke ble sendt inn.
> Flesh out checkboxgroup stories

- packages/react/src/radiogroup/Radio.tsx
- packages/react/src/radiogroup/RadioGroup.stories.tsx
Denne PRen legger inn støtte for å sette description på en enkelt radioknapp. Tidligere har vi kun støttet description på hele radiogruppa, ikke enkelte radioknapper.
Har også endret til at radioknappen alignes til første linje av teksten. Se kodekommentar for hvordan vi får til dette.
> add description support to radio buttons

- packages/react/src/textarea/TextArea.stories.tsx
- packages/react/src/textarea/TextArea.tsx
- packages/react/src/textarea/index.ts
- packages/react/src/textfield/TextField.stories.tsx
[AB#88383](https://dev.azure.com/obosbbl/95fe6e68-b1c5-4e8e-9ebb-fff9d8eeb377/_workitems/edit/88383)
Denne PRen legger til en TextArea komponent.
Det som gjenstår er riktig styling ved fokus og invalid (dette gjelder TextField også). Tar det i en egen PR når det er på plass i Figma.
> Add TextArea component to Grunnmuren v2

- .changeset/grumpy-pans-design.md
- packages/react/src/button/Button.stories.tsx
- packages/react/src/button/Button.tsx
[AB#89294](https://dev.azure.com/obosbbl/95fe6e68-b1c5-4e8e-9ebb-fff9d8eeb377/_workitems/edit/89294)
Figma: https://www.figma.com/file/9OvSg0ZXI5E1eQYi7AWiWn/Grunnmuren-2.0-%E2%94%82-Designsystem?node-id=39%3A182&mode=dev
> Button: add `isIconOnly` support to render button with a single icon

- .changeset/gentle-seas-boil.md
- .changeset/moody-rice-tie.md
- packages/react/package.json
- packages/react/src/select/Select.stories.tsx
- packages/react/src/select/Select.tsx
- packages/react/src/select/index.ts
- packages/react/src/textarea/TextArea.tsx
- packages/react/src/textfield/TextField.tsx
- packages/tailwind/package.json
- packages/tailwind/tailwind-base.cjs
- pnpm-lock.yaml
Denne PRen inkluderer en første versjon av en Select komponent. Denne er helt i startfasen, da den ikke er helt ferdig skisset opp i Figma, så det kommer nok endringer her etter hvert.
Legger også til [tailwind-animate](https://github.com/jamiebuilds/tailwindcss-animate) pluginet. R[AC støtter animation states](https://react-spectrum.adobe.com/react-aria/styling.html#css-animations) som vi kan targete med Tailwind. Lagt til fade in/ut på nedtrekkslisten til Selecten.
> Add Select component

- .changeset/pretty-geckos-rush.md
- .changeset/slimy-meals-sin.md
- packages/react/package.json
- packages/react/src/classes.ts
- packages/react/src/combobox/Combobox.stories.tsx
- packages/react/src/combobox/Combobox.tsx
- packages/react/src/combobox/index.ts
- packages/react/src/select/Select.tsx
- packages/react/src/textarea/TextArea.tsx
- packages/react/src/textfield/TextField.stories.tsx
- packages/react/src/textfield/TextField.tsx
- packages/tailwind/package.json
- pnpm-lock.yaml
Dette startet som en PR på combobox, som endte opp med å touche de fleste formkomponentene.
Combobox består jo egentlig av en input og en select dropdown, men da jeg implementerte comoboxen var det umulig å gjenbruke stilene fra disse. Det endte dermed opp som en refaktorering med deling av stiler mellom TextField, TextArea, Combobox og Select.
Har samtidig fikset litt focus/invalid-stilene til alle de nevnte komponentene, da den bare halvferdig tidligere pga uferdig design.
Burde kanskje vært en egen PR, men har også oppgradert til nyeste Tailwind (under arbeidet med denne PRen brukte jeg noe av den nye funksjonaliteten fra 3.4, men gikk bort fra det igjen...
Merk at dette bare er en initial implementasjon av Combobox, det kommer nok mer etter hvert.
Ser også for meg at på sikt så tilbyr …
> Combobox and field refactoring

- .changeset/honest-coins-allow.md
- .changeset/weak-ties-perform.md
- form-demo/app/uncontrolled/SubmitButton.tsx
- form-demo/app/uncontrolled/page.tsx
- package.json
- packages/icons-react/package.json
- packages/icons-react/tsconfig.json
- packages/react/README.md
- packages/react/package.json
- packages/react/src/button/index.ts
- packages/react/src/index.ts
- packages/react/src/utils/useClientLayoutEffect.ts
- packages/react/tsconfig.json
- pnpm-lock.yaml
Denne PRen blir den siste før vi pusher en ny canary release. Den har følgende endringer:
Re-eksporter `<Form />` fra RAC - https://react-spectrum.adobe.com/react-aria/Form.html. Denne trengs for arbeidet som er gjort i https://github.com/code-obos/grunnmuren/pull/683, og vi vil ikke at konsumentene våre må ha en direkte avhengighet til RAC.
Bytt ut [unbuild](https://github.com/unjs/unbuild/) for pakketering/bundling av pakkene til fordel for [bunchee](https://github.com/huozhi/bunchee). Grunnen til dette er at bunchee har innebygget støtte for React server components, så den klarer å preserve `use client`;  og `use server;` direktiver ved å spytte ut egne chunks for disse. Dette gjør at `<Button />` komponenten vår nå kan brukes i en Next app uten at konsumenten må legge til `use …
> Switch bundler and bundle to single file.

- .changeset/config.json
- form-demo/package.json
changeset klikker totalt når en pakke eller app ikke har version. Legger også til ignore på form-demo i changesets sin config så den ikke driver og oppdaterer den.
> Add version to form-demo to fix changeset

- .changeset/kind-ladybugs-doubt.md
- .storybook/preview.js
- .storybook/preview.tsx
- packages/react/README.md
- packages/react/src/index.ts
Denne PRen legger til støtte for I18nProvideren til React Aria Components.
Denne skal wrappe applikasjonen slik at RAC benytter riktige translation strings for diverese innebygde hjelpetekster. Den pårvirker også ting som tallformateringen i [NumberField](https://react-spectrum.adobe.com/react-aria/NumberField.html#numberfield) (som jeg tenker er en komponent vi legger til støtte for snart).
Her er et eksempel på Storybooken før og etter endringen:
Før, uten I18nProvider i Storybook:
Etter, med I18nProvider i Storybook, med locale satt til `nb`:
Kommer en oppfølgings-PR hvor jeg legger til dokumentasjon for [build utilen som fjerner unødvendige locales](https://react-spectrum.adobe.com/react-aria/internationalization.html#optimizing-bundle-size).
> add I18nProvider to configure the locale

- .changeset/olive-flowers-film.md
- packages/react/package.json
- packages/react/src/button/Button.tsx
- packages/react/src/checkbox/Checkbox.tsx
- packages/react/src/checkbox/CheckboxGroup.tsx
- packages/react/src/combobox/Combobox.tsx
- packages/react/src/radiogroup/Radio.tsx
- packages/react/src/radiogroup/RadioGroup.tsx
- packages/react/src/select/Select.tsx
- packages/react/src/textarea/TextArea.tsx
- packages/react/src/textfield/TextField.tsx
- pnpm-lock.yaml
Denne PRen legger til støtte for ref forwarding. Dette burde gjøre det enklere å bruke skjemakomponentene sammen med for eksempel react-hook-form.
> add forwadRef support

- .changeset/twenty-suns-move.md
- package.json
- packages/react/src/button/Button.tsx
- packages/react/src/utils/useClientLayoutEffect.ts
- pnpm-lock.yaml
Vi hadde plassert `use client` direktivet vårt feil for Button. Det hører hjemme i selve Button-komponenten, ikke i `useClientLayoutEffect`. Button komponenten bruker ting som bare funker på klienten, som useState og useRef etc.
Dette fikser forhåpentligvis problemet med at konsumenter av Grunnmuren alltid måtte bruke `use client` dersom de brukte knappen.
Oppgraderer også Bunchee. Jeg så at i den versjonen vi hadde så cleanet den ikke dist-mappa under bygging, det gjør den nå.
> fix: add missing 'use client'; directive to Button

- packages/tailwind/README.md
Button legges som en `.js`-fil. Med gammel scan blir dermed ikke styling riktig på button.
> Update node_modules scan in tailwind config

- .changeset/lemon-swans-hug.md
- packages/react/src/classes.ts
Fann denna issuen: https://github.com/tailwindlabs/tailwindcss.com/issues/1135
Provat i ios 16 på browserstack, och det fungerar. 
Provat i localhost på chrome, och där ser allt likt ut som innan
Chrome
iOS 16 (broswerstack)
> fix invisible ring

- .changeset/grumpy-parents-cough.md
- packages/react/src/classes.ts
- packages/react/src/internals/InputAddonDivider.tsx
- packages/react/src/internals/index.ts
- packages/react/src/numberfield/NumberField.tsx
- packages/react/src/textfield/TextField.tsx
Denne PRen fikser noen problemer med addons på TextField.
Det var problemer med manglende spacing mellom addon og inputfeltet, dersom addonen din var kun tekst, og ikke et element. Fontstørrelsen på addonen er også feil, så det ser misaligned ut:
```
<TextField leftAddon="(+47)"  label="Telefonnummer" />
```
Tidligere var det noen ikke så smarte forsøk på en blanding av paddings og margins for å støtte margins. Ved å gå over til `gap` fikses problemet og ting blir litt enklere.
> fix: TextField addon issues

- .changeset/honest-items-tap.md
- .storybook/main.js
- .storybook/preview.tsx
- form-demo/app/layout.tsx
- package.json
- packages/react/README.md
- packages/react/src/GrunnmurenProvider.tsx
- packages/react/src/index.ts
- pnpm-lock.yaml
Denne PRen fjerner re-eksporten av I18nProvideren fra RAC, til fordel for vår egen GrunnmurenProvider. Dette er en breaking change, men det det er egentlig bare en rename, og vi er fortsatt i canary-releases.
I RAC versjon 1.0.0 var det et `use client;` direktiv i den publiserte modulen. Dette fjernet de igjen i versjon 1.0.1 til fordel for [`client-only` modulen](https://www.npmjs.com/package/client-only). 
Det gjør at når vi reeksporterer I18nProvideren, så må konsumenten plutselig plutselig legge inn `use client` i all sin egen kode der de har Grunnmuren imports, uansett om det bruker client only features eller ikke. Dette gjør at vi foreløpig ikke har oppdatert til RAC 1.1.1. Vi har lyst til å legge inn `use client` selv der det gir mening, slik at det blir enklere for konsumentene av …
> Remove I18nProvider in favor of GrunnmurenProvider

- .changeset/lucky-masks-rescue.md
- packages/react/package.json
- packages/react/src/GrunnmurenProvider.tsx
- packages/react/src/alertbox/Alertbox.tsx
- packages/react/src/button/Button.tsx
- packages/react/src/index.ts
- pnpm-lock.yaml
Denne PRen oppdaterer React Aria-avhengighetene våre.
Som diskutert legges det også inn et `use client;` direktiv i barrel-fila til Grunnmuren, for bedre kompabilitet med RSC. RAC shippet tidligere med et 'use client;' direktiv selv, men det har de fjernet.
I framtiden, dersom vi får komponenter som ikke nødvendigvis har interaktivitet på klientsiden får vi vurdere å splitte opp til to barrelfiles, en med use client og en uten.
> update react aria deps

- .changeset/small-lies-turn.md
- packages/react/src/backlink/Backlink.tsx
Fikser sånn at hover-style appliseres også når man hover over noe annet enn teksten i backlink
> Applies hover when any part of a Backlink is hovered

- .changeset/dry-boats-tap.md
- packages/react/src/backlink/Backlink.tsx
Gjør at focus-visible funker slik at vi kun får fokusmarkering ved tastaturnavigering. Det er noe i den innebygde RAC link komponenten som gjør at focus-visible stylingen også vises ved klikk på `Backlink`.
> Replace RAC link with native HTML anchor element

- .changeset/shaggy-adults-vanish.md
- packages/react/src/backlink/Backlink.tsx
Sørger for at custom underline også virker når linker brekker over flere linjer:
Uten denne endringen blir det sånn her med lange tekster:
> Support underline on multiline in backlinks

- .changeset/dull-days-pretend.md
- packages/react/src/accordion/Accordion.tsx
Denne PRen setter font-størrelsen til headingen i Accordionen til 1rem (16px).
Dette for å forhindre at "globale heading styles" påvirker headingen.
Slik ser det ut på medlemssidene akkurat nå, hvor det er CSS som setter h4-elementer til 20 px. Se her https://www.obos.no/medlem/medlemsservice/sporsmal-og-svar/om-medlemskap-i-obos:
Mens egentlig skal de være 16 px, som her:
> Accordion: set font size for heading

- .changeset/pink-olives-look.md
- packages/react/src/classes.ts
with a smaller font size in input fields, iOS will automatically zoom in on the field.
Se https://obos.slack.com/archives/C03FR05FJ9F/p1713434756897919
Løser https://dev.azure.com/obosbbl/Content%20hub/_workitems/edit/98781.
Edit: Denne løser også https://github.com/code-obos/grunnmuren/pull/691
> fix: increase font size for input fields to prevent zooming

- package.json
> Use v 9.1.0 of pnpm

- packages/tailwind/tailwind-base.cjs
Denne PRen oppdaterer font-weights og blockquote-font størrelse slik at det matcher det som er her https://www.figma.com/design/TfmnVMUgkpsNEZdhttQYZU/Proposjoner-og-komposisjon?node-id=581-3322&m=dev
Ingen changeset, da de forrige endringene på typography ikke er relaset, og dette bygger bar videre på det arbeidet somer gjort der.
> typography: update font weights

- .changeset/giant-sloths-grab.md
- packages/react/src/classes.ts
Denne PRen passer på at form inputs som Select og Textarea har hvit bakgrunn.
Fikser https://obos.slack.com/archives/C03FR05FJ9F/p1716800143200029
> fix: textarea/select should have a white background

- .changeset/clever-frogs-breathe.md
- packages/tailwind/tailwind-base.cjs
Denne PRen legger tilbake layout-klassene `.page-layout` og `.page-layout-main` som ved en feil ble fjernet i v2.
Når disse kommer igjen så burde det fikse utseendet på de sidene hvor innholdet på siden ikke er høyt nok til å dytte footeren ned mot bunn av skjermen.  Bank-teamet har nevnt det noen ganger for oss nå.
> fix: add back layout classes that diseappeared in v2

- .changeset/modern-apricots-invite.md
- packages/react/src/checkbox/Checkbox.stories.tsx
- packages/react/src/checkbox/Checkbox.tsx
- packages/react/src/checkbox/CheckboxGroup.stories.tsx
- packages/react/src/checkbox/CheckboxGroup.tsx
- packages/react/src/combobox/Combobox.stories.tsx
- packages/react/src/combobox/Combobox.tsx
- packages/react/src/numberfield/NumberField.tsx
- packages/react/src/radiogroup/RadioGroup.stories.tsx
- packages/react/src/radiogroup/RadioGroup.tsx
- packages/react/src/select/Select.stories.tsx
- packages/react/src/select/Select.tsx
- packages/react/src/textarea/TextArea.stories.tsx
- packages/react/src/textarea/TextArea.tsx
- packages/react/src/textfield/TextField.stories.tsx
- packages/react/src/textfield/TextField.tsx
Denne PRen fikser https://obos.slack.com/archives/C03FR05FJ9F/p1716390149188459
Grunnen til at dette sluttet å funke er fordi det har vært en endring under panseret på RAC som har truffet oss. Før så fungerte native validering selv om isInvalid var satt til false, men nå gjør isInvalid valideringen "controlled", og den overstyrer da native validering.
Den kjappe fiksen her er bare å passe på at isInvalid er `undefined` inn til RAC.
Egentlig burde vi hatt visuelle snapshot tester eller lignende for det her, men det har vi ikke akkurat nå, og det tar dessverre litt tid å få på plass også.
Edit:
Se forskjellen her
Før: https://obos-grunnmuren.netlify.app/?path=/story/textfield--required
Etter: https://deploy-preview-846--obos-grunnmuren.netlify.app/?path=/story/textfield--required
> fix: missing error messages for form fields with native validation

- .changeset/loud-apples-tie.md
- packages/tailwind/tailwind-base.cjs
Kjapp followup fiks etter forrige release.
I v1 vi element styling på h1-h5. Dette gikk vi bort fra i v2, men vi har fortsatt en compat mode for dette (`legacyV1Compatibility`).
Dermed må vi sette eksplisitt font på de mindre heading størrelsene ellers blir følgende tilfeller feil i compat mode:
```
// Is rendered with OBOSDisplay, even though it should be OBOSText
<h1 className="heading-m">
```
> fix: explicitly set font-family for all headings

- .changeset/weak-turkeys-teach.md
- packages/react/src/backlink/Backlink.tsx
Legger til manglende `cursor-pointer` på Backlink, slik at den oppfører seg som andre linker ved hover.
> fix(backlink): add cursor pointer

- .changeset/small-shoes-greet.md
- packages/react/src/breadcrumbs/Breadcrumb.tsx
Lenkesmulene i breadcrumbs-komponenten hadde ikke custom fokus-stiler, dermed ble browser defaults brukt.
All klikking på en lenke gir en outline
Fokusring bare synlig ved tastaturnavigering
> fix(breadcrumbs): remove outline, use focus-visible for focus ring

- .changeset/cyan-kangaroos-poke.md
- packages/react/src/alertbox/Alertbox.stories.tsx
- packages/react/src/button/Button.stories.tsx
- packages/react/src/button/Button.tsx
Denne PRen endrer vår Button-komponent til å bruke Button og Link-primitivene fra react-aria-components. Dette som avtalt i https://obos.slack.com/archives/C03FR05FJ9F/p1719491526889589.
Dette gjør at knappen kan integreres bedre med resten av react-aria-components, og det gjør også at når knappen brukes som en anchor/link så fungerer den med `navigate` propen i `GrunnmurenProvider` (på lik linje med feks Backlink og Breadcrumbs-komponentene).
Merk at dette gjør at `onClick` på Button nå må skrives om til `onPress`. Det er fordi det er det det heter i RAC.
Inspirasjon for selve implementasjonen er tatt herfra https://github.com/figma/sds/blob/main/src/ui/utils/AnchorOrButton.tsx
> Button: use react-aria-components primitives

- .changeset/twelve-pumas-report.md
- packages/react/src/backlink/Backlink.stories.tsx
- packages/react/src/backlink/Backlink.tsx
Denne PRen legger til støtte for at Backlink kan rendres som enten en button eller en anchor, basert på om det blir sendt inn en href eller ikke.
Dette er delvis inspirert av det vi gjorde for Button her https://github.com/code-obos/grunnmuren/pull/870.
Fikser https://dev.azure.com/obosbbl/Content%20hub/_boards/board/t/Designsystem%20-%20Grunnmuren/Stories?workitem=96988
> backlink: render as button when no href is provided

- .changeset/hot-clocks-return.md
- .changeset/six-moles-fly.md
- packages/react/src/checkbox/Checkbox.tsx
- packages/react/src/radiogroup/Radio.tsx
Erstatter dummy-`span` med padding og negativ margin for å sikre god klikkflate på checkbox og radio:
Det ble litt forskjellig på checkbox og radio. Radioknapper har display grid, med en gap til en wrapper-`div` som gjør at de ikke trenger `padding-right` for at klikkflaten skal bli stor nok når de brukes uten `children`:
Mens checkbox har ikke det, og trenger dermed både `padding-right` og `padding-left`:
Siden `span`-en som var der fra før brukte `-left-2.5` for å gi minst 44 px bredde brukte jeg samme spacing for paddingen. Og da føltes det naturlig å bruke samme `padding` for `py` og. Det gjorde også at høyden gikk fra 42 px til 46 px (ideelt er minst 44 px). Så slang det med som en bonus i denne PR-en
> Fix radio click area

- .changeset/swift-jars-wave.md
- packages/react/src/backlink/Backlink.tsx
- packages/react/src/button/Button.tsx
Hvis bruker sender inn undefined som href, så vet ikke RAC om det er en a-tag eller Button. Den tror det er en a-tag, men rendrer til slutt bare en span med rolle=link som blir feil. Den skal egentlig rendre en Button da det ikke er en a-tag lenger siden href er undefined. 
Raskeste fiksen, men kan godt skrive det mer eksplisitt
koden:
Rendrer:
Før:
Etter:
> Button: render button if href is undefined

- .changeset/friendly-boats-fold.md
- packages/react/src/classes.ts
> Fix input height on Safari mobile

- .changeset/tender-walls-beg.md
- packages/react/src/classes.ts
Fikser problem med at scrollbar og borders på popover til å tegnes opp riktig i alle browsere. Vi gjorde en fiks med clip-path og outline som funket i noen browsere. Men har fortsatt vært et issue i Safari (hvis brukeren har eneblet scrollbars) og chrome på ubuntu: [891](https://github.com/code-obos/grunnmuren/issues/891)
Safari, før:
Safari nå:
> Fix border on popover

- .changeset/friendly-dolls-protect.md
- packages/react/src/button/Button.stories.tsx
- packages/react/src/button/Button.tsx
Fjerner `bg-white` fra `<Button variant="secondary"/>`. Dette gjør at disse knappene ser bra ut mot en hvilken som helst lys bakgrunn, ikke bare hvit. Mens man fortsatt har mulighet til å bruke `<Button variant="mint"/>` eller `<Button variant="white"/>` mot en mørk bakgrunn.
> Secondary button

- .changeset/dull-houses-confess.md
- packages/react/README.md
- packages/react/src/GrunnmurenProvider.tsx
Denne PRen legger til støtte for `useHref` hooken til [React Aria's RouterProvider](https://react-spectrum.adobe.com/react-aria/routing.html#routerprovider) til vår GrunnmurenProvider.
Det gjør det enklere å integrere Grunnmuren med client side routere som Next når man for eksempel har en custom basepath satt.
__Før__
```tsx
import Link from 'next/link';
import { Button } from '@obosbbl/grunnmuren-react';
// Notice how you have to handle the basepath yourself with Grunnmuren's component, but not with Next's.
<Link href="/bli-medlem">Bli medlem</Link>
<Button href="/medlem/bli-medlem">Bli medlem</Button>
```
__Etter__
```js
// app/providers.tsx
'use client'
import { GrunnmurenProvider } from '@obosbbl/grunnmuren-react';
import { useRouter } from 'next/navigation';
export function …
```
> feat: add `useHref` hook to GrunnmurenProvider

- packages/react/src/alertbox/Alertbox.stories.tsx
- packages/react/src/alertbox/Alertbox.tsx
Siden `isDismissed` var satt som default `false` gjorde det at alle stories der `<Alertbox>` er "_dismissable_" også at de ble _"controlled dismissable"_:
https://github.com/user-attachments/assets/b6296a4d-3810-477b-8a20-2d1e5159eeca
Dette funker bedre nå:
https://github.com/user-attachments/assets/3cba0051-4a97-4005-b312-89afead44ae6
Har ikke laget noe changeset, da dette ikke er en fiks i selve pakken. Men kun storybook.
P.S. 
Egen PR på å fikse fokusmarkering (`focus-visible`) er på vei....
> Make alertboxes uncontrolled dismissable

- .changeset/khaki-buttons-impress.md
- packages/react/src/badge/Badge.stories.tsx
- packages/react/src/badge/Badge.tsx
- packages/react/src/badge/index.ts
- packages/react/src/index.ts
Denne PRen legger til en ny komponent, `<Badge />`.
[Figma-lenke](https://www.figma.com/design/9OvSg0ZXI5E1eQYi7AWiWn/Grunnmuren-2.0-%E2%94%82-Designsystem?node-id=3762-2595&node-type=frame&m=dev).
[Live preview eksempel](https://deploy-preview-937--obos-grunnmuren.netlify.app/?path=/docs/badge--docs)
Det er mulig å justere både størrelse og farge, og den sizer også ikoner automatisk. Merk at denne komponenten aldri skal brukes som et interaktivt element, tenk på det mer som en merkelapp. Kan brukes på feks Cards, bilder eller andre steder.
Den erstatter den gamle Chip komponenten fra v1:
> feat: Badge component

- .changeset/quiet-insects-tickle.md
- packages/react/src/GrunnmurenProvider.tsx
- packages/react/src/alertbox/Alertbox.tsx
- packages/react/src/index.ts
- packages/react/src/use-locale.ts
Denne PRen legger  til en hook, `useLocale()` som returnerer `locale` satt i `<GrunnmurenProvider />`.
Jeg PoCet litt på en kart-komponent i går, og trengte tilgang til språk/locale. Da føltes det rart ut at jeg skulle hente det via react-aria, når min avhengighet er til Grunmmuren. Derfor gir det mening at vi eksponerer en hook for dette (som vi også har nytte av internt i grunnmuren).
> add useLocale hook

- .changeset/green-stingrays-vanish.md
- packages/react/src/classes.ts
Setter alltid hvit farge på input, slik at vi overstyrer grå bakgrunn på `type="search"` i Safari:
Dette problemet kan ses f.eks. i boligsøket i Safari på iPhone:
> Fix input bg color

- .changeset/giant-balloons-search.md
- packages/react/src/accordion/Accordion.tsx
Klassen `group` ble nok brukt på et tidspunkt i implementasjonen av `<Accordion>`. Men den brukes ikke lenger. Og den skaper problemer når man nester innhold som også har (anonym) `group`, som f.eks. `<Select>`.
> Remove redundant class

- packages/react/src/card/Card.stories.tsx
- packages/react/src/card/Card.tsx
- packages/react/src/card/index.ts
- packages/react/src/content/Content.tsx
- packages/react/src/index.ts
Legger til "bare minimum" for en `<Card>` komponent. 
Her det satt opp litt grunnleggende styling for kort. Og kun en variant for `border`. I følge Kristian så er bakgrunnsfarge veldig fritt, så har ikke lagt opp til noe annet enn at dette styres med `className` for nå.
Basert på erfaringene i [denne draften](https://github.com/code-obos/grunnmuren/pull/962) virker det lurt å wrappe tekstlig innhold i en container (bruker `<Content>` til dette). Dette vil forenkle veldig hvis vi skal legge tilrette for horisontal layout senere.
> Basic Card

- packages/react/src/card/Card.stories.tsx
- packages/react/src/card/Card.tsx
- packages/react/src/content/Content.tsx
Legger til støtte for ikoner og bilder (i vertikal layout) på `<Card>`.
Har også lagt inn stories for demonstrasjon av kort med ikoner i bunn/topp.
Det er lagt til en ny komponent `<Media>` i `content`. Den kan brukes for å wrappe komponenter som `<img>`, `<Image> `(fra Next) en custom-komponent f.eks. `<CloudinaryImage>`, `<svg>` eller en `<video>`. Kort og godt alt av komponenter som er bilder, illustrasjoner eller video.
Her har man mulighet til å velge aspect-ratio, som settes med tailwind sin innebygde `aspect`-util. Måtte legge til `w-full` for at det skal funke i FF (som beregner implisitt bredde på en litt annen måte). Det er god support for `aspect-ratio `([94.59%](https://caniuse.com/?search=aspect-ratio)). Så spørs hva vi tenker om det? Et alternativ her hadde kanskje vært å …
> Vertical icon and image cards

- .github/workflows/main.yml
- .github/workflows/release.yml
- package.json
Upgrade GHA and engines field to use node 22, since it's in LTS now.
> Use node 22

- packages/react/src/card/Card.stories.tsx
- packages/react/src/card/Card.tsx
- packages/react/src/content/Content.tsx
Legger til støtte for klikkbare kort gjennom å eksponere en `href`-prop på `<Card>`. Hele kortet blir gjort klikkbart ved å wrappe `children` til `<Heading>` i en `<Link>`. 
https://github.com/user-attachments/assets/a0458753-0275-45c5-9a92-825424c9d77a
Det er også lagt til rette for at konsumenten skal kunne plassere andre klikkbare elementer i kortet, som fortsatt skal være klikkbare i seg selv. For å legge tilrette for en så god brukeropplevelse som mulig mtp. klikkflate, har jeg lagt til rette for at man kan bruke `<Footer>` for å skille ut andre klikkbare elementer. Men jeg har også lagt inn en failsafe, i tilfelle noen skulle ha behov for å plassere klikkbare elementer andre steder i kortet.
Stylingen for `<Footer>` blir litt kompleks, men jeg syns det var den _minst_ komplekse …
> Clickable card

- .changeset/clever-geckos-press.md
- form-demo/app/uncontrolled/SubmitButton.tsx
- packages/react/src/__stories__/FormValidation.stories.tsx
- packages/react/src/button/Button.stories.tsx
- packages/react/src/button/Button.tsx
* use [isPending](https://react-spectrum.adobe.com/react-aria/Button.html#pending) in RAC for better screen reader support for buttons that are in a loading/pending state
* Deprecate isLoading in favor of isPending (this aligns with both RAC's naming convention and [React's useActionState hook](https://react.dev/reference/react/useActionState))
* Use text transparency for the button content instead of state/layoutEffect to maintain the button's size while in a pending state.
Note that when the button is in a pendingstate it can't be interacted with. This means you don't have to disable a button to prevent multiple submissions etc. Note that our Button component also can render a RAC Link, which technically doesn't support isPending. It will render to look the same as a pending button, but …
> Button: use isPending instead of isLoading

- .changeset/popular-jobs-drum.md
- packages/react/src/card/Card.tsx
Øker line-height på `<CardLink>` slik at custom underline aligner med teksten når den brekker over flere linjer.
> Increase line-height on CardLink

- .eslintrc.json
- biome.json
- packages/icons-react/scripts/make-react-icons.mjs
- packages/icons-react/scripts/utils.mjs
- packages/icons-svg/scripts/figma-import.mjs
- packages/icons-svg/scripts/optimize.mjs
- packages/icons-svg/scripts/utils.mjs
- packages/tailwind/fonts/generate-font-fallback.ts
- packages/tailwind/tailwind-base.cjs
Denne PRen fortsetter arbeidet med å migrere fra eslint til biome.
pakkene `icons-react`, `icons-svg` og `tailwind` flyttes over.
Det betyr at bare `react` er igjen på eslint. Når den er over kan vi fjerne eslint helt.
> move more linting to biome

- .changeset/config.json
- apps/docs/package.json
~~Det ser ut som at grunnen til at bygget for `changeset` feiler på grunn av at pakken `apps/docs` er private og mangler `version`. Så prøver meg på det som en fiks.~~
Vi ignorer den pakken i `changeset`-config istedenfor (forlsag fra @alexanbj) 
Se: [https://github.com/changesets/changesets/pull/847](https://github.com/changesets/changesets/pull/847)
> Ignore docs apps in changesets

- apps/docs/package.json
Får fortsatt feilen `error TypeError: Cannot read properties of null (reading 'prerelease')` selv etter ignore av docs-pakken. Prøver å legge til et `version`-felt.
> Add version field

- README.md
- apps/docs/.gitignore
- apps/docs/README.md
- apps/docs/app/routes/__root.tsx
- apps/docs/app/routes/ikoner.tsx
- apps/docs/app/routes/index.tsx
- apps/docs/app/ui/main-nav.tsx
- apps/docs/package.json
- pnpm-lock.yaml
Denne PRen fortsetter arbeidet med ikonsiden. Åpner denne PRen nå, før jeg gjør for mye greier 😅
Kommer mer etter hvert!
Endringer:
* Lagt til litt enkle kort på forsiden for å få det til å se litt bedre ut.
* Gjort at innholdet strekker seg nedover hele skjermen, med footeren i bunn.
* Lagt til/oppdatert READMEs
* Lagt til støtte for å laste ned ikonene.
* Skrevet litt dokumentasjon for ikonene.
Merk at måten ikonene kommer over i public mappen for nedlastning nå er via en enkel `cp` command. Den vil ikke fungere på feks windows. For at nedlastningslenkene på ikonene skal fungere må dette npm scriptet kjøres manuelt første gang man kjører appen.
Prøvde litt raskt å ta i bruk [vite-plugin-static-copy](https://www.npmjs.com/package/vite-plugin-static-copy) slik at vi får det som en del av …
> More work on icons page

- apps/docs/app/routes/__root.tsx
- apps/docs/app/routes/ikoner.tsx
Denne PRen integrererer RAC Links med TanStack Router. Dette enabler client side routing selv om vi bruker en RAC/Grunnmuren Link i stedet for TanStack sin egen. Se https://react-spectrum.adobe.com/react-aria/routing.html
Det gjør også at vi får ta nytte av TanStack Router sine typesafe routes.
Flytter også på GrunnmurenProvider slik at den wrapper sidenav og footer, før wrappet den kun `<Outlet />`
Før:
Etter:
Når jeg satte opp dette så viser det seg at det er en feil i typelogikken i Grunnmuren. Egentlig skal `download` propen kun være tilgjengelig når `href` er satt til Button, men dette ser ikke ut til å funke 🤔 Ser på det i en egen PR.
> docs: add bridge between RAC and TanStack router

- .changeset/chatty-bags-exist.md
- packages/tailwind/tailwind-base.cjs
Vi overstyrer Tailwind sine font family utilties til å bruke OBOS fonten, eg `font-display`og `font-text` i stedet for Tailwind sine default `font-sans` og `font-serif`. Se https://tailwindcss.com/docs/font-family
Det betyr at vi fjernet `font-mono` utilen. Monospaced fonter er nyttig i for eksempel kodeeksempler, som vi trenger i Grunnmurens dokumentasjon. Siden OBOS ikke har en monospaced font inkluderer vi Tailwind sin default her.
> tailwind: add back default `font-mono` utility

- apps/docs/app/routeTree.gen.ts
- apps/docs/app/routes/komponenter/button.tsx
- apps/docs/app/ui/component-preview.tsx
- apps/docs/package.json
- pnpm-lock.yaml
Legger til generell komponent som kan brukes for kode-eksempler, med funksjonalitet for å kopiere koden. Bruker [react-live](https://commerce.nearform.com/open-source/react-live/) til dette, som er en lettvekts-pakke for code-snippets.
For at det skal være litt enklere å skrive kode-eksemplene har jeg også lagt inn `react-element-to-jsx-string`, som gjør det mulig å skrive eksemplene som JSX.
Har også lagt til en custom theme som jeg syns var litt finere enn defaulten:
https://github.com/user-attachments/assets/1d41b76b-26aa-4d06-97e8-5cb41a2e58cc
Neste steg her tenker jeg er å fikse en props-tabell som kan kobles sammen med både kodeeksempler og rendering.
Dette er kun en første minimi-versjon, og vi burde (akkurat som på ikoner) fikse størrelsen på kopier-knappen.
Har lagt fokus på å få …
> Add code snippet component to button

- apps/docs/app.config.ts
Disabler minification av funksjoner og variabler, slik at komponent-navn ikke blir borte i kode-eksempler. Dette er en litt brute, midlertidig fiks.
> Disable minification of component names

- apps/docs/app/routes/komponenter/badge.tsx
Adds code snippet examples to the `Badge` docs. Very simliar examples to those in the [storybook](https://obos-grunnmuren.netlify.app/?path=/docs/badge--docs).
This follows the same pattern as the code snippet examples for the `Button` component.
> Add code examples

- apps/docs/app/routes/komponenter/button.tsx
- packages/react/src/button/button.tsx
Ads a props table to the bottom of the `button` docs.
Had to tweak the props typing on the button component to enable `docgen` to parse the props. From what I can tell the type is just the same with this change, only difference is that`docgen` is able to auto generate alle the types for us. I suspect either the `typeof` keywoid or the generic `ComponentPropsWithoutRef` was the problem.
> Props table on button

- .changeset/twelve-hats-jam.md
- packages/react/src/card/card.tsx
Enables auto hyphens on card headings, to prevent overflow in narrow cards or headings with longer words. Adds the necessary classes both on the `heading` slot and the`card-link` slot, to make it work with and without interactive headings (where the content is wrapped in a `card-link`).
To make this work in Safari and FF we need to set `word-break: break-word`.
> Auto hyphenate card headings

- .changeset/gold-owls-call.md
- packages/react/src/content/content.tsx
Trodde dette egentlig ble fikset av https://github.com/code-obos/grunnmuren/pull/1054, men viste seg at problemet var at disse komponentene aldri ble wrappet av forwardRef, og dermed ble typesignaturen off...
Dette burde fungere nå. Verifisert ved at @theodorSchei har testet output etter denne fiksen på sin maskin hvor han fortsatt hadde dette issuet.
> fix: add forwardRef to Content and Heading components

- apps/docs/package.json
Workaround to bypass `gitignore` on the `docgen` output file. The `--ignore-path` option unsets the default ignore (`.prettierignore` and `.gitignore`). Since this command is only executed on this file alone, we can safely bypass the ignore files.
This solves a problem discussed here https://github.com/code-obos/grunnmuren/pull/1059#discussion_r1888624791
> Enforce formatting on docgen output file

- .github/workflows/release.yml
Release workflowen feilet etter at vi la inn @code-obos pakker i docs-appen.
I teorien kan vi endre workflowen til at den er satt opp med github registry i setup-node reusable workflow, men samtidig så trenger release kun å forholde seg til packages (som ikke benytter noen private pakker), ikke docs appen.
Prøver dermed dette for å se om det fungerer. Kanskje det shaver av litt tid også?
> ci: fix release action after github registry

- apps/docs/app/routes/_docs/komponenter/badge.tsx
- apps/docs/app/routes/_docs/komponenter/button.tsx
- apps/docs/app/ui/component-preview.tsx
Our `<ComponentPreview>` component relies on `react-element-to-jsx-string`, that currently doesn't support React 19. So passing a React.Element to the code prop will just render every JSX element as `<UnknownElementType>`.
There is work in progress on adding support for React 19 in `react-element-to-jsx-string`: https://github.com/algolia/react-element-to-jsx-string/pull/865.
Until that is in place we can use strings for the code snippets. By allowing strings for the `code` prop in `<ComponentPreview>` we support both JSX and string snippets. This makes it possible to work around the problem by passing strings for now (short term), and also makes the API  more flexible (long term).
The drawback of using strings is that we don't get auto formatting and no help from TypeScript. But since …
> Fix code snippets

- .changeset/grumpy-ducks-turn.md
- packages/react/src/card/card.tsx
Adds support for all RAC `<Link>` props on the `<CardLink>` component. This enables passing events such as `onPress` for tracking.
The type has been modified to allow either a `href` prop in combination with any other RAC Link prop, or no `href` with just `className` or `children` props. Thie ensures that the type safety matches the implementation: if a `href` is passed it renders as a `<Link>`, if not it renders as a `<div>`. Note that we we can't utilize that the `<Link>` component from react-aria-components renders as a `<span>` if it doesn't have a `href`, because it still renders with `role="link"` and `tabindex="0"` which makes it focusable and announced as a link by screen readers.
> Support all RAC link props on CardLink

- apps/docs/schema.json
- apps/docs/studio/objects/content.ts
- apps/docs/studio/objects/live-code-block.ts
- apps/docs/studio/objects/static-code-block.ts
- apps/docs/studio/schema-types.ts
Adds two separate implementations of the code-block field: _static_ and _dynamic_.
Static code blocks renders as simple code snippets that don't control rendering or allows for live editing.
This is handy for simple getting started scripts like:
``` bash
pnpm i @obosbbl/grunnmuren-react
```
Dynamic code blocks renders as code snippets that can control rendering and allows for live editing/live updates.
This is handy for demo examples where you want to render a component based on the code snippet:
``` tsx
<Badge color="blue" size="large">
large
</Badge>
```
> Support both static and dynamic code snippets

- .changeset/lazy-ducks-roll.md
- packages/react/src/backlink/backlink.tsx
- packages/react/src/breadcrumbs/breadcrumb.tsx
- packages/react/src/button/button.tsx
Adds support for type safe routes as values for the `href` prop on `<Backlink>`, `<Breadcrumb>` and `<Button>`.
By basing the `href` prop on the RAC `LinkProps` `href` property, we ensure that type safety works on routes:
<br/>
<br/>
<br/>
<br/>
<br/>
> Fix href types

- apps/docs/app.config.ts
- apps/docs/app/routes/_docs/ikoner.tsx
- apps/docs/app/routes/_docs/komponenter/index.tsx
- apps/docs/package.json
- apps/docs/tsconfig.json
TanStack Start kjører ikke TSC som en del av build, slik Next gjør.
Legger dermed inn dette selv. Dette hjelper oss også å sikre at vi ikke knekker ting i Grunnmuren, ref href på CardLink.
Måtte legge til noen ignores for å få dette til å funke. Og kunne fjerne en annen ignore etter https://github.com/code-obos/grunnmuren/pull/1082
> docs: run typecheck

- apps/docs/app/routes/_docs/komponenter/$slug.tsx
- apps/docs/app/ui/component-preview.tsx
- apps/docs/app/ui/content.tsx
- apps/docs/app/ui/props-table.tsx
Renders code examples for all components based on Sanity data.
A bit unsure if this is the path we want to go down.
By making the code "block content" we need to deal with it as portable text. This means we have define our own component type for the `PortableText` component. Since we also need to pass context to the `ComponentPreview`, we have agreed to just include all the Grunnmuren components in the `ComponentPreview` as a default. This way we can render any component, even as new components are added or some even deleted over time.
With this change we also affect the Button component, since they share the same render page (`$slug`). So this PR changes both those component docs to only render code examples from Santiy, and removes the hard coded ones.
> WIP examples from sanity data

- .changeset/two-moles-watch.md
- packages/react/src/card/card.stories.tsx
- packages/react/src/card/card.tsx
Changes from grid to flex layout on the `<Card>` component. As this makes styling easier. Let's say for example if you have multiple Cards side by side, where you want them to have equal height. But the size of the content varies:
Also making a small adjustment on the examples with a footer, which makes more sense (if a layout like shown above is desired)
Without this change, you would typically end up dealing with this issue:
> Make it easier to style cards

- apps/docs/app/ui/props-table.tsx
Reduces font size for the props table to the same as the font size of the code example (`14px`/`0.875rem`)
> Reduce font size to 14px

- .github/workflows/release.yml
- package.json
Usikker på hvorfor dette repoet har det, men ingen andre vi har changesets har `install` som en del av `version`. Kan hende det har noe med prereleases/canary å gjøre, men vi gjør et forsøk uten..
> ci: attempt to fix release workflow

- apps/docs/app/ui/code.tsx
- apps/docs/app/ui/component-preview.tsx
- apps/docs/app/ui/content.tsx
Extract code snippet into a new `<Code/>` component that can be used for both editable code snippets with live preview, and static code snippets.
Not completely happy with the API of `<Code/>`, as it sort of "magically" requires the value to be controlled when enabling live edit with preview (this is to keep the code value in sync if a user edits it, and then wants to copy it). Maybe it would be better to just move that state into the `<Code/>` component itself (removing it from `<ComponentPreivew/>`). But then again for static code examples would end up being set up with a state that never updates, which also feels wrong.
https://github.com/user-attachments/assets/4e8e17c3-158f-45de-9599-2eb1ce61a03b
> Add component for static code snippets

- .changeset/mighty-candles-press.md
- packages/react/src/content/content.tsx
- packages/react/src/index.ts
- packages/react/src/video-loop/index.ts
- packages/react/src/video-loop/video-loop.tsx
Adds a new `<VideoLoop/>` component that can play a muted video that loops (similar to a gif). The component respects reduced motion settings for users that have this setting enabled (typically users with vestibular motion disorders). And will not autoplay for these users. It ensures further accessibility by requiring a visible or invisible description (`alt` or `caption`) of the video content. Play/pause button is of course keyboard accessible with a click area corresponding to the entire video size. The video itself is hidden from screen readers, but the texts passed to the `alt` and `caption` props are read by screen readers. Only `caption` is visible.
The pause button only shows when hovering or focusing the video. But the play button will always show, as long as the video is paused. …
> Add VideoLoop component

- pnpm-lock.yaml
Release of the package is currently failing due lockfile out of sync.
Seems like `pnpm-lock` is out of sync, with the version of `icons-react` being one step behind the current version (after [this](https://github.com/code-obos/grunnmuren/pull/1134) was merged). Seems like it somehow got the wrong version in the [changeset](https://github.com/code-obos/grunnmuren/pull/1134/files#diff-882ee4e1622e2f899e9cab54225ec983ea25a9aae0359abdbae3c4dd5804d72cR3).
> Fix icons-react version

- .changeset/slimy-jobs-cough.md
- packages/react/package.json
- pnpm-lock.yaml
Denne PRen gjør at vi ikke pinner CVA til en spesifikk beta versjon, men heller tillater hvilken som helst av betaversjonene. Det er samme vi gjør her https://github.com/code-obos/grunnmuren-extended/blob/7d7a818a72ea651f3e4e2256f44685deea2cc23e/packages/map/package.json#L30
Dette for å forhindre at folk ender opp med flere versjoner av CVA i dependency treet sitt.
> grunnmuren-react: don't pin cva version

- .changeset/silly-rings-mix.md
- packages/react/src/alertbox/alertbox.stories.tsx
- packages/react/src/alertbox/alertbox.tsx
Denne PRen legger til mulighet for å overstyre default ikonet for en alertbox variant:
Merk at dette er funskjonalitet som skal brukes varsomt. Variantene har forskjellige farger knyttet til seg, men for folk med fargeblindhet kan det være ikonet som avgjør typen alert, eg warning eller info.
> alertbox: add icon prop to override the default icon

- apps/docs/app/routes/_docs.tsx
- apps/docs/app/routes/_docs/komponenter/$slug.tsx
- apps/docs/app/routes/_docs/komponenter/index.tsx
- apps/docs/app/ui/main-nav.tsx
- apps/docs/app/ui/sanity-content.tsx
- apps/docs/sanity.types.ts
- apps/docs/schema.json
- apps/docs/studio/documents/component.ts
Denne PRen legger til støtte for å markere en komponent som ny i dokumentasjonen. Dette er inspirert av NAV https://aksel.nav.no/komponenter/core/formsummary.
Tanken er at det skal synliggjøre hva som nytt i designsystemet vårt.
> docs: highlight component as "new"

- .changeset/new-chefs-chew.md
- apps/docs/app/ui/sanity-content.tsx
- packages/tailwind/tailwind-base.cjs
Set the font weight for all `<strong>` in Portable Text tags to `medium`:
> Use correct font-weight on strong

- .changeset/funny-pillows-listen.md
- packages/tailwind/tailwind-base.cjs
Add custom styling for inline `<code>` in prose:
As designed by Kristian.
> Override default prose code styles

- apps/docs/app/ui/code.tsx
Hides the code in each example of the docs using the `<Disclosure>` component. No fancy styling here, we might want to make it pop a bit more (maybe it should be som form of CTA?). But that is something that can be refined later, after discussing it in the team.
The main purpose of this PR is to just get rid of A LOT of "noise" from alle the displayed code examples. And _then_ we can tweak the design of the "Code Disclosure" in a new PR.
https://github.com/user-attachments/assets/fb95f22a-1bd1-42db-811f-72ac51cc540f
> Hide code in disclosure

- .github/workflows/cd.yml
- .github/workflows/main.yml
- .storybook/main.js
- Dockerfile
- README.md
- apps/docs/.gitignore
- package.json
- postcss.config.js
- tailwind.config.js
- tailwind.config.ts
Denne PRen flytter hosting av storybook fra netlify til docs appen vår.
Da får vi samlet alt på et sted, i stedet for å ha noe via Netlify og noe via Azure.
Dette gjør også at vi får ryddet opp i alle feilende PRer på grunn av at Netlify ikke liker at vi har spesifisert Node 22 som en engine.
En ulempe er at vi ikke da lenger vil få preview deploys av storybook på PRer, men det får vi bare leve med.
Hvis jeg har satt opp dette riktig kommer storybooken til å serves fra https://grunnmuren.obos.no/storybook.
Merk at for å få denne til å kjøre måtte jeg kommentere ut kjøringen av storybook-testrunneren. Merger denne allikevel, da jeg per nå betaler for hostingen av netlify fra egen lomme. Vi får se på test-kjøring i neste uke når folk er tilbake fra vitnerferie.
> Move storybook hosting to docs app

- .changeset/early-clubs-peel.md
- packages/react/src/badge/badge.tsx
- packages/react/src/card/card.stories.tsx
- packages/react/src/card/card.tsx
Makes it possible to use the existing `<Badge>` component to create a badge that overlays the `<Media>` content of a `<Card>`.
It follows the border radius of the `Card` and can be either left or right aligned (based it's nth-child index):
- If it is the _first-child_ it will be **left aligned**
- If it is the _last-child_ it will be **right aligned**
> Overlay badge in Card Media

- .changeset/polite-candies-draw.md
- packages/react/src/card/card.stories.tsx
- packages/react/src/card/card.tsx
Adding support for horizontal layout in the `<Card>` component with a new `layout` prop.
This works for arbitrary compositions, where the combination of `<Content>` and `<Media>` as children renders a slightly different layout of the `<Card>` than if `<Content>` is combined with other types of children, such as an `svg` or `<Icon>`.
The exceptions for horizontal `<Card>` with `<Media>` as a child is that it renders a 50/50 split for the `Media` and `Content`. And that responsiveness is handled by a media query (for now, we will use a container query once we migrate to tailwind 4 and there is better support for container queries)
https://github.com/user-attachments/assets/f2afe771-35ec-4ed3-bf93-9b291a47e743
https://github.com/user-attachments/assets/cd18dd93-623d-456a-b728-4722d52fb5a4
> Horizontal card layout

- apps/docs/app/ui/code.tsx
First step in making the examples stand out more in the docs.
Components are consistently horizontally centered in a bordered "frame", with a vertical spacing.
The "view code" button is rendered inside this "frame":
There are some things that needs to be fixed in the `Discolsure` komponent before this looks good enough. But that is out of scope for this PR.
> docs: add borders for the examples

- .changeset/cool-kings-hunt.md
- packages/react/src/backlink/backlink.tsx
Propsen syntes ikke på backlink! Det berodde nog på att typen till React.ComponentPropsWithoutRef<typeof Link> verkade vara problematisk. Samma skedde på button, och löstes med å bruke RACLinkProps istället!
> fix props for backlink

- .changeset/mean-boxes-sort.md
- packages/react/src/card/card.tsx
Adding a failsafe until we start using container queries as breakpoints for the horizontal `<Card>` layout.
> Failsafe for image radius in horizontal Card

- apps/docs/app/ui/code.tsx
Removes the rendering of `caption` in code examples
> Do not render caption

- .changeset/plenty-parts-mate.md
- packages/react/src/disclosure/disclosure.stories.tsx
- packages/react/src/disclosure/disclosure.tsx
Change the way in which spacing in the `<DisclosurePanel>` is managed.
The previous implementation was based on the styles for [`<Accordion>`](https://github.com/code-obos/grunnmuren/blob/main/packages/react/src/accordion/accordion.tsx#L145-L156). This spacing is very specific to the `<Accordion>` component, and pseudo-elements are used there to avoid wrapping the content in yet another `<div>`.
The `<Disclosure>` component however, should be much more flexible. It should be possible for the consumer to set _any_ desired spacing (padding, margin etc.) in the `<DisclosurePanel>`. The only way to do this (while still keeping the grid transition animation for the expand/collapse effect) is to wrap the panel in one extra div.
> Fix disclosure panel spacing

- apps/docs/app/routes/_docs/komponenter/$slug.tsx
- apps/docs/app/ui/table-of-contents-nav.tsx
Adding shortcuts to the right hand side of the docs. This is a start, and something that we can continue to work on as we make the docs responsive. 
The navigation is sticky, using anchor tags that target each heading.
> Add short cuts menu

- .changeset/tender-melons-lose.md
- packages/react/src/card/card.tsx
This enables more flexible layouts in the `<Media>` component in `<Card>`.
This was not possible before, due to a work-around for Firefox: setting `w-full` on _every_ child in the `<Media>` component.
This is now solved by only targeting any immediate `img` child of `<Media>`, which is the only case where it is necessary for Firefox to respect the `aspect-ratio`.
> Make media css more predictable

- .changeset/public-hounds-leave.md
- packages/react/src/card/card.tsx
Decrease break point in horizontal `<Card>` without `<Media>`
This should be more appropriate for current known use cases.
> Adjust breakpoint

- apps/docs/app/ui/table-of-contents-nav.tsx
Denne PRen legger til nesting av ToC i Grunnmuren dokumentasjonen.
Dette gjør det enklere å scanne innholdsfortegnelsen. Har lagt inn støtte for h2 og h3. Eventuelle mindre heading ignoreres fra innholdsfortegnelsen.
> docs: add nesting to ToC

- apps/docs/app/routes/_docs/$slug.tsx
- apps/docs/app/routes/_docs/index.tsx
- apps/docs/app/routes/_docs/komponenter/$slug.tsx
- apps/docs/app/routes/_docs/komponenter/index.tsx
- apps/docs/app/routes/_docs/profil/farger.tsx
- apps/docs/app/routes/_docs/profil/ikoner.tsx
- apps/docs/app/routes/_docs/profil/index.tsx
Adding equal spacing above and below `<h1>` tags in the docs. It would be closer to `my-9` in figma, but that just looks off next to the OBOS logo in the menu. So increasing it a bit made it look more deliberant
> Add top spacing

- apps/docs/app/routes/_docs/komponenter/$slug.tsx
Hides table of contents `nav` on small screens
> hide table of contents nav on small view screens

- .changeset/odd-yaks-switch.md
- apps/docs/app/styles/app.css
- biome.json
- packages/tailwind/README.md
- packages/tailwind/font.css
- packages/tailwind/fonts/generate-font-fallback.ts
- packages/tailwind/package.json
- packages/tailwind/tailwind-base.css
The font fallback is now included as a default standard. Since it doesn't really make sense not having it. If there is need for the fallback to be optional, we can enable that further down the road. But until now one intermediate workaround would be to override the tailwind theme variables:
``` CSS
/** global.css */
@theme {
--font-text: OBOSText, sans-serif;
--font-display: OBOSDisplay, sans-serif;
}
```
> Remove font-fallback as an option

- packages/react/src/accordion/accordion.tsx
- packages/react/src/backlink/backlink.tsx
- packages/react/src/badge/badge.tsx
- packages/react/src/breadcrumbs/breadcrumb.tsx
- packages/react/src/breadcrumbs/breadcrumbs.tsx
- packages/react/src/button/button.tsx
- packages/react/src/checkbox/checkbox-group.tsx
- packages/react/src/checkbox/checkbox.tsx
- packages/react/src/combobox/combobox.stories.tsx
- packages/react/src/combobox/combobox.tsx
- packages/react/src/content/content.tsx
- packages/react/src/numberfield/numberfield.tsx
- packages/react/src/radiogroup/radio-group.tsx
- packages/react/src/radiogroup/radio.tsx
- packages/react/src/select/select.tsx
- packages/react/src/textarea/textarea.tsx
- packages/react/src/textfield/textfield.tsx
Removes `ref` forwarding as it is no longer necessary (since we dropped support for React 18)
> Remove ref forwarding

- .changeset/fuzzy-pillows-call.md
- packages/react/src/accordion/accordion.tsx
Removes the TS workaround for the `inert` prop in the `<Accordion>` implementation. This has been fixed in React 19.
This PR can not be merged until we have dropped support for React 18.
> Remove TS workaround on inert prop

- packages/tailwind/package.json
Removes internal `fonts` folder from files in `package.json` - these files are only used to build the font.css file.
> Remove internal fonts folder

- .changeset/clear-rings-think.md
- packages/react/src/checkbox/checkbox-group.tsx
- packages/react/src/checkbox/checkbox.tsx
- packages/react/src/combobox/combobox.tsx
- packages/react/src/numberfield/numberfield.tsx
- packages/react/src/radiogroup/radio-group.stories.tsx
- packages/react/src/radiogroup/radio-group.tsx
- packages/react/src/select/select.tsx
- packages/react/src/textarea/textarea.tsx
- packages/react/src/textfield/textfield.tsx
Fixes the logic behind validation states for inputs, where passing `errorMessage=""` would set the field in an invalid state. This doesn't really make sense, and can cause strange validation behaviour when using libraries like Zod. With this change setting `errorMessage` to `"" | null | undefined` is now equivalent: the field is valid, unless combined with the `isInvalid` prop set to `true`.
``` tsx
<TexField isInvalid/>
```
``` tsx
<TexField errorMessage="Something went wrong"/>
```
``` tsx
<TexField isInvalid errorMessage="Something went wrong"/>
```
``` tsx
<TexField isInvalid errorMessage=""/>
```
``` tsx
<TexField isInvalid errorMessage={null}/>
```
``` tsx
<TexField isInvalid errorMessage={undefined}/>
```
``` tsx
<TexField/>
```
``` tsx
<TexField isInvalid={false}/>
```
``` tsx …
```
> Fix error message validation logic

- .changeset/stupid-paths-matter.md
- packages/tailwind/tailwind-base.css
Sets the correct line-height for the heading-s class on small screens.
> Fix line-height for heading-s

- packages/react/src/file-upload/file-upload.stories.tsx
Updates examples for FileUpload used in Form, to filter out the "dummy file object" persisted in FormData by the browser throught the `getAll` API.
See: [https://grunnmuren.obos.no/komponenter/file-upload#b0cfafd73e91](https://grunnmuren.obos.no/komponenter/file-upload#b0cfafd73e91)
> Filter out empty dummy file object in from examples

- .changeset/cold-hats-drive.md
- packages/react/src/radiogroup/radio-group.tsx
Fixes an accessibility issue with the `<RadioGroup>` component, where passing `value=""` as a prop caused the radio input to get `tabindex="-1"`. Which would make it inaccessible to keyboard and screen reader users.
> Fix tabindex bug

- .changeset/shaggy-cycles-go.md
- packages/react/src/file-upload/file-upload.tsx
Må sende med fileType som options hvis man lager ny fil ellers ender det opp med "" streng og octet-stream i server actions hos oss
eksempel:
> add fileType to new File in fileupload

- .changeset/real-dryers-jog.md
- packages/react/src/carousel/carousel.tsx
- packages/react/src/hero/hero.tsx
Setting up responsive aspect ratios for `<Media>` content in `<Hero>` and `<Carousel>`. This was handled the same way as for the `full-bleed` variant before, but the `full-bleed` is actually an exception. Since that is the only case where aspect ratio does not make sense (100% width is arbitrary, while the height is given).
The change is most notable for the `two-column` variant.
https://github.com/user-attachments/assets/eeef0cac-ec46-463c-a0ae-e03e873d2152
https://github.com/user-attachments/assets/6757f977-aced-4073-ac17-5a69b14ea7d8
https://github.com/user-attachments/assets/2e829031-0ae1-45d2-8de8-ca11944dd400
https://github.com/user-attachments/assets/a6021d72-68a4-4658-ab67-aab2317a06a4
> Use responsive aspect ratios for Media

- .changeset/tangy-laws-eat.md
- packages/react/src/__stories__/typography.stories.tsx
- packages/tailwind/tailwind-typography.css
Denne PRen legger til `prose-white` som brukes for å style `prose` til å bruke hvit tekst. Da kan den brukes på feks mørkeblå-bakgrunner:
Merk at jeg ikke har brukt tid å gjøre en full override for hvit. Tror ikke vi bruker feks kdb-elementer, så sånne ting får fikses ved behov.
Fjernet også en del ubrukte custom properties som henger igjen fra da vi inlinet typography-pluginet.
> Prose white

- packages/react/src/tabs/tabs.tsx
Use `grid` instead of `flex` for `<Tabs>` to prevent unitended inherited layout issues such as:
With this fix:
> Use grid instead of flex

- apps/docs/package.json
- apps/docs/src/routes/_docs.tsx
- apps/docs/src/routes/_docs/$slug.tsx
- apps/docs/src/routes/_docs/komponenter/$slug.tsx
- apps/docs/src/routes/_docs/profil/ikoner.tsx
- apps/docs/src/ui/props-table.tsx
- apps/docs/src/ui/scroll-to-top.tsx
- pnpm-lock.yaml
Because we have very long articles on the grunnmuren docs, we thought it would be nice with a "scroll to top"- button! 
* Added a "scroll to top" button that appears after scrolling down 300px, using the `ArrowUp` icon. The button is fixed to the bottom-right corner and smoothly scrolls the page to the top when clicked.
**Fixes not related:**
* Wrapped the props table in a horizontally scrollable container to improve usability on smaller screens.
* Simplified the main documentation page layout by removing the unnecessary `grid` class from the container, relying on `flex` for layout.
> Scroll to top

- .changeset/loud-showers-walk.md
- packages/react/src/tag-group/tag-group.tsx
Highlight selected tags with more than just color. This is to meet [WCAG SC 1.4.1](https://www.w3.org/WAI/WCAG22/Understanding/use-of-color.html)
A selected / removable `Tag` is now also highlighted with increased `font-weight` and `stroke-width` on it's icons:
> Highlight selected tags with more than just color

- .changeset/sad-rabbits-nail.md
- packages/react/src/link-list/link-list.stories.tsx
- packages/react/src/link-list/link-list.tsx
New `LinkList` component. Can be used to display a set of releated links where it is possible to choose between rendering regular, download or external links on each `LinkListItem`. The `LinkListItem` uses `Link` from react aria components under the hood. Which means it aslo supports `routerOptions`. Refer to [https://react-spectrum.adobe.com/react-aria/routing.html](https://react-spectrum.adobe.com/react-aria/routing.html).
``` tsx
import {
UNSAFE_LinkList as LinkList,
UNSAFE_LinkListItem as LinkListItem,
} from './link-list';
```
``` tsx
<LinkList>
<LinkListItem href="/bolig">Bolig</LinkListItem>
<LinkListItem href="/bank">Bank</LinkListItem>
<LinkListItem href="/medlem">Medlem</LinkListItem>
</LinkList>
```
``` tsx
<LinkList>
<LinkListItem download href="/">
Medlemsvilkår …
```
> New LinkList component

- .changeset/new-goats-bow.md
- packages/react/src/link-list/link-list.tsx
Fixes layuout issues when `LinkList` is rendered inside `flex` or `grid`-containers. Also ensures a passing of the `className` prop that makes sense (while also preventing overrides on `LinkListItem`
> Layout fixes

- .changeset/grumpy-rice-mate.md
- packages/react/src/card/card.tsx
Use the newly added layout-gap-x in horizontal `<Card>` components that contains `<Media>`, keep the same gap for other horizontal `<Card>` components:
https://github.com/user-attachments/assets/009ebb0e-b96c-4bcd-879d-d18483d1f5ab
> Adjust row-gap for image cards

- .changeset/small-jeans-sing.md
- packages/react/src/hero/hero.tsx
Increase from 280px to 320px to get better aspect-ratio on small screens
https://github.com/user-attachments/assets/b3565fcf-6810-484c-b51a-c5f5bf8dd3e2
> Increase full width media height on small screens

- .changeset/moody-knives-hunt.md
- packages/react/src/index.ts
- packages/react/src/link/index.ts
- packages/react/src/link/link.stories.tsx
- packages/react/src/link/link.tsx
* Added a new `Link` component in `link.tsx`, extending `react-aria-components`'s `Link` with custom styling and focus management for accessibility and design consistency.
* Created Storybook stories in `link.stories.tsx` to showcase various usages of the new `Link` component, including default, external, with icon, custom styling, and embedded in text.
**Exports and package integration:**
* Updated `index.ts` to export the new `Link` component, ensuring it is available from the main package entry point.
* Added an export file in the `link` directory to re-export the new `Link` component, supporting modular imports.
Fokus:
> Add link component

- .changeset/common-spoons-reply.md
- packages/tailwind/tailwind-typography.css
Align link styles in prose with the `<Link>` component from grunnmuren-react for consistency.
> Update link styles in prose to match Link component

- .changeset/cute-webs-move.md
- packages/tailwind/tailwind-typography.css
Enhance the typography by adding styles for `<h5>` elements in the prose component, ensuring consistent formatting across headings.
> Fix `<h5>` styles in `prose` for consistent typography
